// SPDX-FileCopyrightText: 2026 Jake Wehmeier (BTSpaniel)
// SPDX-License-Identifier: MIT
// Output: addons/flow/flow_host_webgpu.d.mts
// Generated by tools/generate_addon_types.py; edit this reviewed template.
/// <reference path="../../types/webgpu.d.ts" />
import type { PhysXModule } from '../../bridge/physx-bulk.mjs';
/** Standard WebGPU objects use the pinned, unmodified gpuweb declarations. */
export type NumericArray = readonly number[] | Float32Array | Float64Array | Int32Array | Uint32Array | Uint16Array | Int16Array | Uint8Array | Int8Array;
export type Vec3 = readonly [number, number, number] | Float32Array | Float64Array;
export type Quaternion = readonly [number, number, number, number] | Float32Array | Float64Array;
/** New rebase methods require a plain array; typed arrays are not admitted. */
export type FlowRebaseShift = readonly [number, number, number];
export type FlowScalarChannels = readonly [number, number, number, number] | Float32Array | Float64Array;
/** Planes use dot(normal, localPosition) <= distance. */
export type FlowPlane = readonly [number, number, number, number] | Float32Array | Float64Array;
export type FlowSolidBoundary = {
    id: number; layer?: number; position?: Vec3; quaternion?: Quaternion;
    enabled?: boolean; resetMotion?: boolean; terminalExchange?: boolean;
} & (
    { type: 'sphere'; radius: number } |
    { type: 'box'; halfSize: Vec3 } |
    { type: 'plane' } |
    { type: 'convex'; planes: readonly FlowPlane[]; bounds: readonly [Vec3, Vec3] }
);
export interface FlowScalarSource {
    id: number; layer?: number; type?: 'box'; enabled?: boolean;
    position?: Vec3; quaternion?: Quaternion; halfSize: Vec3;
    /** Integrated normalized-channel*m^3/s; only the temperature channel may be negative. Not SI heat. */
    totalRates: FlowScalarChannels;
}
export interface FlowScalarSourceReceipt {
    frame: number; dt: number;
    sources: {
        id: number; admittedSamples: number; sampleCount: number;
        requested: number[]; applied: number[]; deferred: number[];
    }[];
}
export interface FlowGasCell {
    readonly cell: readonly [number, number, number, number];
    readonly position: FlowRebaseShift; readonly velocity: FlowRebaseShift;
    /** Explicit positive layer density times cell volume, in kg. */
    readonly mass: number; readonly layer: number; readonly volume: number; readonly w: number;
}
export interface FlowGasContact {
    readonly gas: number; readonly shape: number; readonly layer: number;
    readonly face: number; readonly normal: FlowRebaseShift;
}
declare const rebaseTokenBrand: unique symbol;
declare const momentumTokenBrand: unique symbol;
/** Deeply frozen view of an opaque, owner-bound, single-use WeakMap identity.
 * Runtime validation also rejects foreign, stale, reused and concurrent tokens.
 * The declaration brand is compile-time only; it is not a runtime property.
 */
export interface FlowRebaseToken {
    readonly [rebaseTokenBrand]: never;
    readonly shift: FlowRebaseShift; readonly coordinateEpoch: number;
}
export interface FlowMomentumToken {
    readonly [momentumTokenBrand]: never;
    readonly gas: readonly FlowGasCell[]; readonly contacts: readonly FlowGasContact[];
}
export interface FlowRebaseReceipt {
    status: 'REBASED'; abi: 1; shift: [number, number, number]; coordinateEpoch: number; advancedTime: 0;
}
/** Host scatter acknowledgement only. Engine normal-exchange work/heat ledgers are separate.
 * No heat obligation is deposited into the Flow thermal field by this method.
 */
export interface FlowMomentumReceipt {
    status: 'EXCHANGED'; abi: 1; cells: number; contacts: number; advancedTime: 0;
}
/** Rejects observable promise-returning coordinators. TypeScript cannot recover promises
 * hidden by a void/unknown annotation; runtime checks still enforce synchronous commit.
 * The coordinator must be prevalidated and must not throw. Post-commit faults are terminal.
 */
export type FlowSynchronousCoordinator<F extends () => unknown = () => void> =
    F & ([Extract<ReturnType<F>, PromiseLike<unknown>>] extends [never] ? unknown : never);
export interface FlowLayer {
    id: number;
    cellSize?: number;
    gravity?: Vec3;
    pressure?: boolean;
    combustion?: boolean;
    vorticity?: number;
}
export interface FlowEmitterFields {
    id: number;
    layer?: number;
    enabled?: boolean;
    applyPostPressure?: boolean;
    position?: Vec3;
    quaternion?: Quaternion;
    velocity?: Vec3;
    temperature?: number;
    fuel?: number;
    smoke?: number;
    burn?: number;
    divergence?: number;
    coupleRateVelocity?: number;
    coupleRateTemperature?: number;
    coupleRateFuel?: number;
    coupleRateSmoke?: number;
    coupleRateDivergence?: number;
    coupleRateBurn?: number;
}
export type FlowEmitter = FlowEmitterFields & (
    { type?: 'sphere'; radius?: number; allocationScale?: number } |
    { type: 'box'; halfSize?: Vec3; allocationScale?: number } |
    { type: 'points'; positions: NumericArray; velocities?: NumericArray; allocateMask?: boolean } |
    { type: 'mesh'; positions: NumericArray; indices: NumericArray; velocities?: NumericArray; allocateMask?: boolean; minDistance?: number; maxDistance?: number; orientationLeftHanded?: boolean }
);
export type FlowCollider = {
    id: number; layer?: number; position?: Vec3; quaternion?: Quaternion;
    coupleRateVelocity?: number; multisample?: boolean; resetMotion?: boolean; enabled?: boolean;
} & ({ type?: 'sphere'; radius: number } | { type: 'box'; halfSize: Vec3 });
export interface FlowTextureResource {
    kind: 'texture'; texture: GPUTexture; format: GPUTextureFormat;
    dimension: GPUTextureDimension; size: number[]; bytes: number;
}
export interface FlowBufferResource {
    kind: 'buffer'; buffer: GPUBuffer; size: number; memory: number; pointer: number;
}
export interface FlowOutput {
    density: FlowTextureResource;
    velocity: FlowTextureResource | null;
    sparse: FlowBufferResource | null;
    level: number[] | null;
    layer: number[] | null;
    layerAndLevel: number;
    coordinateEpoch: number;
    boundaries?: { buffer: GPUBuffer; size: number; version: number; abi: 1 } | null;
    layers?: { id: number; blockSizeWorld: number[]; layerAndLevel: number }[];
}
export interface FlowStats {
    frames: number; dispatches: number; passes: Record<string, number>;
    activeBlocks: number; allocatedBytes: number; collisionCount: number;
    collisionEnabled: number; collisionMode: 'one-way-native-velocity-obstacle'; velocitySamples?: number;
    rebases: number; uploadWrites: number; uploadBytes: number; uploadChunks: number;
    uploadChunkReuses: number; queueSubmissions: number; textureAllocations: number;
    textureReuses: number; textureResets: number; pooledTextureBytes: number;
    exactRequestedTimeStep?: boolean; scalarSourceCount?: number; scalarSourceAbi?: 1;
    solidBoundaryCount?: number; solidBoundaryEnabled?: number; solidBoundaryAbi?: 1;
}
export interface FlowShader { code: string; reflection: { parameters: readonly unknown[] } }
export class FlowHostWebGpu {
    /** Borrows the device. Caller must serialize step/sample/dispose operations. */
    static create(module: PhysXModule, device: GPUDevice, shaderRoot: string, options?: { maxBlocks?: number; cellSize?: number }): Promise<FlowHostWebGpu>;
    constructor(module: PhysXModule, device: GPUDevice, shaders: Map<string, FlowShader>);
    readonly module: PhysXModule;
    readonly device: GPUDevice;
    readonly stats: FlowStats;
    readonly output: FlowOutput | null;
    readonly handle: number;
    readonly busy: boolean;
    readonly disposed: boolean;
    readonly stateRevision: number;
    readonly fault?: unknown;
    readonly scalarSourceReceipt: FlowScalarSourceReceipt | null;
    /** Native context callback; applications should use the methods below. */
    call(op: number, a: number, b: number, c: number, d: number, e: number, f: number): number | void;
    step(dt?: number): Promise<FlowOutput | null>;
    rebasePeriod(): [number, number, number];
    validateRebase(shift: FlowRebaseShift): true;
    prepareRebase(shift: FlowRebaseShift): Promise<FlowRebaseToken>;
    validatePreparedRebase(token: FlowRebaseToken): true;
    commitPreparedRebase<F extends () => unknown = () => void>(token: FlowRebaseToken, synchronize?: FlowSynchronousCoordinator<F> | null): Promise<FlowRebaseReceipt>;
    rebase(shift: FlowRebaseShift): Promise<FlowRebaseReceipt>;
    /** Explicit Map of layer IDs to positive finite kg/m^3. No normalized smoke-as-mass conversion. */
    prepareMomentumExchange(densities: Map<number, number>, options?: { capacity?: number }): Promise<FlowMomentumToken>;
    validatePreparedMomentum(token: FlowMomentumToken): true;
    /** The outer array must contain every admitted cell once; values must be exactly representable f32.
     * These numeric/lifetime constraints remain runtime checks. No clock is advanced.
     */
    commitPreparedMomentum<F extends () => unknown = () => void>(token: FlowMomentumToken, velocities: readonly Vec3[], synchronize?: FlowSynchronousCoordinator<F> | null): Promise<FlowMomentumReceipt>;
    setEmitter(options?: { position?: Vec3; velocity?: Vec3; radius?: number; temperature?: number; fuel?: number; smoke?: number; enabled?: boolean }): void;
    setScene(scene?: { layers?: FlowLayer[]; emitters?: FlowEmitter[] }): void;
    setColliders(records?: FlowCollider[]): { status: 'CONFIGURED'; abi: 1; mode: FlowStats['collisionMode']; count: number; enabledCount: number };
    setScalarSources(records?: readonly FlowScalarSource[]): void;
    setSolidBoundaries(records?: readonly FlowSolidBoundary[]): { status: 'CONFIGURED'; abi: 1; count: number; enabledCount: number };
    sampleVelocity(positions: NumericArray, options?: { layer?: number }): Promise<Float32Array>;
    setControls(options?: { pressure?: boolean; combustion?: boolean; vorticity?: number }): void;
    dispose(): Promise<void>;
}
export { solidBoundaryWGSL } from './flow_solid_boundary.mjs';
