# SPDX-License-Identifier: MIT
"""Generate NVIDIA Flow host binding headers for its Slang WGSL corpus.

No NVIDIA operator code is translated or replaced. Bytecode is a shader URL
token resolved by the browser NvFlowContext implementation.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def generate():
    output = ROOT / 'work/flow-host-headers'
    for path in sorted((ROOT / 'dist/flow-wgsl').rglob('*.reflection.json')):
        reflection = json.loads(path.read_text())
        name = path.name.removesuffix('.reflection.json')
        params = reflection['parameters']
        fields, writes, resources = [], [], []
        for i, param in enumerate(params):
            kind = param['type']['kind']
            if kind == 'constantBuffer':
                resource, descriptor = 'bufferTransient', 'constantBuffer'
            elif kind == 'samplerState':
                resource, descriptor = 'sampler', 'sampler'
            elif kind == 'resource':
                writable = param['type'].get('access') == 'readWrite'
                texture = param['type']['baseShape'].startswith('texture')
                resource = 'textureTransient' if texture else 'bufferTransient'
                descriptor = ('rwTexture' if writable else 'texture') if texture else ('rwStructuredBuffer' if writable else 'structuredBuffer')
            else:
                raise ValueError((path, kind))
            ctype = {'bufferTransient': 'NvFlowBufferTransient', 'textureTransient': 'NvFlowTextureTransient', 'sampler': 'NvFlowSampler'}[resource]
            fields.append(f'    {ctype}* {param["name"]};')
            writes.append(f'    writes[{i}].type = eNvFlowDescriptorType_{descriptor}; writes[{i}].write.vulkan.binding = {param["binding"]["index"]};')
            resources.append(f'    resources[{i}].{resource} = params->{param["name"]};')
        token = path.relative_to(ROOT / 'dist/flow-wgsl').as_posix().replace('.reflection.json', '.wgsl')
        code = f'''// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct {name}_Pipeline {{ NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; }};
inline void {name}_init(NvFlowContextInterface* iface, NvFlowContext* context, {name}_Pipeline* ptr) {{
    static const char token[] = "{token}";
    NvFlowComputePipelineDesc desc = {{}}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}}
inline void {name}_destroy(NvFlowContext* context, {name}_Pipeline* ptr) {{ ptr->iface->destroyComputePipeline(context, ptr->pipeline); }}
struct {name}_PassParams {{
{chr(10).join(fields)}
}};
inline void {name}_addPassCompute(NvFlowContext* context, {name}_Pipeline* ptr, NvFlowUint3 gridDim, const {name}_PassParams* params) {{
    NvFlowDescriptorWrite writes[{len(params)}] = {{}}; NvFlowResource resources[{len(params)}] = {{}};
{chr(10).join(writes)}
{chr(10).join(resources)}
    NvFlowPassComputeParams pass = {{}}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = {len(params)}; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "{name}";
    ptr->iface->addPassCompute(context, &pass);
}}
'''
        target = output / 'shaders' / (name + '.hlsl.h')
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(code)
    return output


if __name__ == '__main__':
    print(generate())
