// SPDX-FileCopyrightText: 2026 Jake Wehmeier (BTSpaniel)
// SPDX-License-Identifier: MIT
// Output: addons/flow/webgpu_bridge.d.mts
// Generated by tools/generate_addon_types.py; edit this reviewed template.
/// <reference path="../../types/webgpu.d.ts" />
import type { PhysXModule } from '../../bridge/physx-bulk.mjs';
export interface FlowBridgeOptions {
    adapter?: GPUAdapter; device?: GPUDevice; powerPreference?: GPUPowerPreference;
    deviceDescriptor?: GPUDeviceDescriptor;
}
export class FlowWasmWebGpuBridge {
    static create(module: PhysXModule, options?: FlowBridgeOptions): Promise<FlowWasmWebGpuBridge>;
    constructor(module: PhysXModule, adapter: GPUAdapter, device: GPUDevice, ownsDevice: boolean);
    readonly module: PhysXModule;
    readonly adapter: GPUAdapter;
    readonly device: GPUDevice;
    readonly ownsDevice: boolean;
    readonly closed: boolean;
    requireOpen(): void;
    assertHeapRange(pointer: number, byteLength: number): void;
    allocate(byteLength: number): number;
    free(pointer: number): void;
    createStorageBuffer(byteLength: number, extraUsage?: GPUBufferUsageFlags, label?: string): GPUBuffer;
    destroyBuffer(buffer: GPUBuffer): void;
    upload(buffer: GPUBuffer, pointer: number, byteLength: number, bufferOffset?: number): void;
    createComputePipeline(code: string, entryPoint?: string, label?: string): Promise<GPUComputePipeline>;
    dispatch(pipeline: GPUComputePipeline, entries: GPUBindGroupEntry[], workgroups: number | number[], label?: string): void;
    download(buffer: GPUBuffer, pointer: number, byteLength: number, bufferOffset?: number): Promise<void>;
    close(): void;
}
export function runFlowWebGpuRoundTrip(module: PhysXModule, options?: FlowBridgeOptions & { count?: number }): Promise<{
    status: 'FLOW_WEBGPU_WASM_ROUND_TRIP_PASSED'; count: number; byteLength: number;
    stagingAbi: number; simd128: true;
    adapter: { vendor: string; architecture: string; device: string; description: string } | null;
}>;
