#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Compile the first-party conservative additive Flow source passes with Slang."""
import argparse
import json
import subprocess
from pathlib import Path
from compile_wgsl import ROOT, DEFAULT_FLOW_ROOT, DEFAULT_SLANGC, include_paths, shader_sources, narrow_storage_access, license_header, sha256

HERE = Path(__file__).resolve().parent
NAMES = ('PrScalarAdmitCS', 'PrScalarCountCS', 'PrScalarApplyCS', 'PrScalarReceiptCS')


def build(slangc=DEFAULT_SLANGC, *, component='scalar', names=NAMES, prefix='PrScalar', description='Finite additive scalar sources with GPU admission receipts'):
    output = ROOT / 'dist/flow-wgsl/addons' / component
    output.mkdir(parents=True, exist_ok=True)
    includes = [HERE, *include_paths(DEFAULT_FLOW_ROOT, shader_sources(DEFAULT_FLOW_ROOT))]
    rows = []
    for name in names:
        source = HERE / (name + '.hlsl')
        destination = output / (name + '.wgsl')
        reflection = destination.with_suffix('.reflection.json')
        command = [str(slangc), str(source), '-lang', 'hlsl', '-target', 'wgsl', '-entry', 'main', '-stage', 'compute',
                   '-matrix-layout-column-major', '-preserve-params', '-reflection-json', str(reflection)]
        for include in includes:
            command += ['-I', str(include)]
        command += ['-o', str(destination)]
        result = subprocess.run(command, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        if result.returncode:
            raise RuntimeError(name + ':\n' + result.stdout)
        normalized, narrowed = narrow_storage_access(destination.read_text())
        upstream = DEFAULT_FLOW_ROOT / 'include/nvflow/shaders/NvFlowShader.hlsli'
        destination.write_text(license_header(upstream.read_text())
                              + '// First-party source operator: SPDX-License-Identifier: MIT\n// Generated by compile_scalar_wgsl.py.\n' + normalized)
        rows.append({'source': source.relative_to(ROOT).as_posix(), 'sourceSha256': sha256(source),
                     'wgsl': destination.relative_to(ROOT / 'dist/flow-wgsl').as_posix(), 'wgslSha256': sha256(destination),
                     'reflection': reflection.relative_to(ROOT / 'dist/flow-wgsl').as_posix(),
                     'reflectionSha256': sha256(reflection), 'storageAccessNarrowed': narrowed})
        print('PASS: ' + name, flush=True)
    report = {'abi': 1, 'component': description, 'shaders': rows,
              'sourceHashes': {path.name: sha256(path) for path in sorted(HERE.iterdir()) if path.is_file()
                               and (path.name.startswith(prefix) or path.name.startswith('scalar_sources_' if component=='scalar' else 'momentum_exchange_')
                                    or path.name in ('compile_scalar_wgsl.py', 'compile_'+component+'_wgsl.py', 'PrSolidBoundary.hlsli'))}}
    (output / 'manifest.json').write_text(json.dumps(report, indent=2) + '\n')
    return report


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--slangc', type=Path, default=DEFAULT_SLANGC)
    build(parser.parse_args().slangc)
