// SPDX-FileCopyrightText: 2026 Jake Wehmeier (BTSpaniel)
// SPDX-License-Identifier: MIT
// Output: addons/flow/flow_solid_boundary.d.mts
// Generated by tools/generate_addon_types.py; edit this reviewed template.
import type { FlowSolidBoundary } from './flow_host_webgpu.mjs';
/** Validates plain arrays and packs owned ABI1 records. Numeric limits and geometry remain runtime checks. */
export function packSolidBoundaries(records: readonly FlowSolidBoundary[], layers: Set<number>): {
    packet: ArrayBuffer; planes: Float32Array; boundaryLayers: Map<number, number>; enabledCount: number;
};
export function solidBoundaryWGSL(options?: { group?: number; binding?: number; name?: string }): string;
