// SPDX-FileCopyrightText: 2026 Jake Wehmeier (BTSpaniel)
// SPDX-License-Identifier: MIT
// Output: addons/flow/flow_scalar_sources.d.mts
// Generated by tools/generate_addon_types.py; edit this reviewed template.
import type { FlowScalarSource } from './flow_host_webgpu.mjs';
/** Rates are normalized channels times m^3/s, not joules or gas mass. */
export function packScalarSources(records: readonly FlowScalarSource[], layers: Set<number>): {
    packet: ArrayBuffer; sourceLayers: Map<number, number>;
};
