// SPDX-FileCopyrightText: 2026 Jake Wehmeier (BTSpaniel)
// SPDX-License-Identifier: MIT
// Output: bridge/physx-bulk-rust.d.mts
// Generated by tools/generate_addon_types.py; edit this reviewed template.
import { PhysXBulk, type PhysXModule } from './physx-bulk.mjs';
export class PhysXBulkRust extends PhysXBulk {
    constructor(module: PhysXModule, options?: { capacity?: number });
}
