// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct AdvectionDensity1CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void AdvectionDensity1CS_init(NvFlowContextInterface* iface, NvFlowContext* context, AdvectionDensity1CS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/AdvectionDensity1CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void AdvectionDensity1CS_destroy(NvFlowContext* context, AdvectionDensity1CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct AdvectionDensity1CS_PassParams {
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* layerParamsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowTextureTransient* densityIn;
    NvFlowTextureTransient* velocityIn;
    NvFlowSampler* valueSampler;
    NvFlowTextureTransient* densityOut;
};
inline void AdvectionDensity1CS_addPassCompute(NvFlowContext* context, AdvectionDensity1CS_Pipeline* ptr, NvFlowUint3 gridDim, const AdvectionDensity1CS_PassParams* params) {
    NvFlowDescriptorWrite writes[7] = {}; NvFlowResource resources[7] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_texture; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_texture; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_sampler; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_rwTexture; writes[6].write.vulkan.binding = 6;
    resources[0].bufferTransient = params->globalParamsIn;
    resources[1].bufferTransient = params->layerParamsIn;
    resources[2].bufferTransient = params->tableIn;
    resources[3].textureTransient = params->densityIn;
    resources[4].textureTransient = params->velocityIn;
    resources[5].sampler = params->valueSampler;
    resources[6].textureTransient = params->densityOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 7; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "AdvectionDensity1CS";
    ptr->iface->addPassCompute(context, &pass);
}
