// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct AdvectionSimpleCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void AdvectionSimpleCS_init(NvFlowContextInterface* iface, NvFlowContext* context, AdvectionSimpleCS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/AdvectionSimpleCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void AdvectionSimpleCS_destroy(NvFlowContext* context, AdvectionSimpleCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct AdvectionSimpleCS_PassParams {
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* layerParamsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowTextureTransient* valueIn;
    NvFlowSampler* valueSampler;
    NvFlowTextureTransient* valueOut;
};
inline void AdvectionSimpleCS_addPassCompute(NvFlowContext* context, AdvectionSimpleCS_Pipeline* ptr, NvFlowUint3 gridDim, const AdvectionSimpleCS_PassParams* params) {
    NvFlowDescriptorWrite writes[6] = {}; NvFlowResource resources[6] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_texture; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_sampler; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_rwTexture; writes[5].write.vulkan.binding = 5;
    resources[0].bufferTransient = params->globalParamsIn;
    resources[1].bufferTransient = params->layerParamsIn;
    resources[2].bufferTransient = params->tableIn;
    resources[3].textureTransient = params->valueIn;
    resources[4].sampler = params->valueSampler;
    resources[5].textureTransient = params->valueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 6; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "AdvectionSimpleCS";
    ptr->iface->addPassCompute(context, &pass);
}
