// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct AdvectionFadeVelocityCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void AdvectionFadeVelocityCS_init(NvFlowContextInterface* iface, NvFlowContext* context, AdvectionFadeVelocityCS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/AdvectionFadeVelocityCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void AdvectionFadeVelocityCS_destroy(NvFlowContext* context, AdvectionFadeVelocityCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct AdvectionFadeVelocityCS_PassParams {
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* layerParamsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowTextureTransient* velocityIn;
    NvFlowTextureTransient* velocityOut;
};
inline void AdvectionFadeVelocityCS_addPassCompute(NvFlowContext* context, AdvectionFadeVelocityCS_Pipeline* ptr, NvFlowUint3 gridDim, const AdvectionFadeVelocityCS_PassParams* params) {
    NvFlowDescriptorWrite writes[5] = {}; NvFlowResource resources[5] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_texture; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_rwTexture; writes[4].write.vulkan.binding = 4;
    resources[0].bufferTransient = params->globalParamsIn;
    resources[1].bufferTransient = params->layerParamsIn;
    resources[2].bufferTransient = params->tableIn;
    resources[3].textureTransient = params->velocityIn;
    resources[4].textureTransient = params->velocityOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 5; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "AdvectionFadeVelocityCS";
    ptr->iface->addPassCompute(context, &pass);
}
