// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct DebugVolume2CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void DebugVolume2CS_init(NvFlowContextInterface* iface, NvFlowContext* context, DebugVolume2CS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/DebugVolume2CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void DebugVolume2CS_destroy(NvFlowContext* context, DebugVolume2CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct DebugVolume2CS_PassParams {
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* layerParamsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowTextureTransient* densityShadowIn;
    NvFlowSampler* samplerIn;
    NvFlowTextureTransient* coarseDensityShadowOut;
};
inline void DebugVolume2CS_addPassCompute(NvFlowContext* context, DebugVolume2CS_Pipeline* ptr, NvFlowUint3 gridDim, const DebugVolume2CS_PassParams* params) {
    NvFlowDescriptorWrite writes[6] = {}; NvFlowResource resources[6] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_texture; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_sampler; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_rwTexture; writes[5].write.vulkan.binding = 5;
    resources[0].bufferTransient = params->globalParamsIn;
    resources[1].bufferTransient = params->layerParamsIn;
    resources[2].bufferTransient = params->tableIn;
    resources[3].textureTransient = params->densityShadowIn;
    resources[4].sampler = params->samplerIn;
    resources[5].textureTransient = params->coarseDensityShadowOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 6; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "DebugVolume2CS";
    ptr->iface->addPassCompute(context, &pass);
}
