// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EllipsoidRasterCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EllipsoidRasterCS_init(NvFlowContextInterface* iface, NvFlowContext* context, EllipsoidRasterCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EllipsoidRasterCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EllipsoidRasterCS_destroy(NvFlowContext* context, EllipsoidRasterCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EllipsoidRasterCS_PassParams {
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* layerParamsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowBufferTransient* arrayValuesIn1;
    NvFlowBufferTransient* arrayValuesIn4;
    NvFlowBufferTransient* blockIdxIn;
    NvFlowBufferTransient* rangeIn;
    NvFlowBufferTransient* instanceIdIn;
    NvFlowTextureTransient* valueOut;
};
inline void EllipsoidRasterCS_addPassCompute(NvFlowContext* context, EllipsoidRasterCS_Pipeline* ptr, NvFlowUint3 gridDim, const EllipsoidRasterCS_PassParams* params) {
    NvFlowDescriptorWrite writes[9] = {}; NvFlowResource resources[9] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_structuredBuffer; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_structuredBuffer; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_rwTexture; writes[8].write.vulkan.binding = 8;
    resources[0].bufferTransient = params->globalParamsIn;
    resources[1].bufferTransient = params->layerParamsIn;
    resources[2].bufferTransient = params->tableIn;
    resources[3].bufferTransient = params->arrayValuesIn1;
    resources[4].bufferTransient = params->arrayValuesIn4;
    resources[5].bufferTransient = params->blockIdxIn;
    resources[6].bufferTransient = params->rangeIn;
    resources[7].bufferTransient = params->instanceIdIn;
    resources[8].textureTransient = params->valueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 9; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EllipsoidRasterCS";
    ptr->iface->addPassCompute(context, &pass);
}
