// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterMeshGenSortKeysCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterMeshGenSortKeysCS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterMeshGenSortKeysCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterMeshGenSortKeysCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterMeshGenSortKeysCS_destroy(NvFlowContext* context, EmitterMeshGenSortKeysCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterMeshGenSortKeysCS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* arrayValuesIn;
    NvFlowBufferTransient* bounds4In;
    NvFlowBufferTransient* sortKeyOut;
    NvFlowBufferTransient* sortValOut;
};
inline void EmitterMeshGenSortKeysCS_addPassCompute(NvFlowContext* context, EmitterMeshGenSortKeysCS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterMeshGenSortKeysCS_PassParams* params) {
    NvFlowDescriptorWrite writes[6] = {}; NvFlowResource resources[6] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[5].write.vulkan.binding = 5;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gSubStepParams;
    resources[2].bufferTransient = params->arrayValuesIn;
    resources[3].bufferTransient = params->bounds4In;
    resources[4].bufferTransient = params->sortKeyOut;
    resources[5].bufferTransient = params->sortValOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 6; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterMeshGenSortKeysCS";
    ptr->iface->addPassCompute(context, &pass);
}
