// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterPointMarkCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterPointMarkCS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterPointMarkCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterPointMarkCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterPointMarkCS_destroy(NvFlowContext* context, EmitterPointMarkCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterPointMarkCS_PassParams {
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowTextureTransient* voxelWeightOut;
};
inline void EmitterPointMarkCS_addPassCompute(NvFlowContext* context, EmitterPointMarkCS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterPointMarkCS_PassParams* params) {
    NvFlowDescriptorWrite writes[3] = {}; NvFlowResource resources[3] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_rwTexture; writes[2].write.vulkan.binding = 2;
    resources[0].bufferTransient = params->globalParamsIn;
    resources[1].bufferTransient = params->tableIn;
    resources[2].textureTransient = params->voxelWeightOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 3; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterPointMarkCS";
    ptr->iface->addPassCompute(context, &pass);
}
