// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterPointScan1CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterPointScan1CS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterPointScan1CS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterPointScan1CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterPointScan1CS_destroy(NvFlowContext* context, EmitterPointScan1CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterPointScan1CS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* reduceTarget1In;
    NvFlowBufferTransient* reduceCouple1In;
    NvFlowBufferTransient* reduceWeight1In;
    NvFlowBufferTransient* key1In;
    NvFlowBufferTransient* scanTarget2In;
    NvFlowBufferTransient* scanCouple2In;
    NvFlowBufferTransient* scanWeight2In;
    NvFlowBufferTransient* key2In;
    NvFlowBufferTransient* scanTarget1Out;
    NvFlowBufferTransient* scanCouple1Out;
    NvFlowBufferTransient* scanWeight1Out;
};
inline void EmitterPointScan1CS_addPassCompute(NvFlowContext* context, EmitterPointScan1CS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterPointScan1CS_PassParams* params) {
    NvFlowDescriptorWrite writes[13] = {}; NvFlowResource resources[13] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_structuredBuffer; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_structuredBuffer; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_structuredBuffer; writes[8].write.vulkan.binding = 8;
    writes[9].type = eNvFlowDescriptorType_structuredBuffer; writes[9].write.vulkan.binding = 9;
    writes[10].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[10].write.vulkan.binding = 10;
    writes[11].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[11].write.vulkan.binding = 11;
    writes[12].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[12].write.vulkan.binding = 12;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gSubStepParams;
    resources[2].bufferTransient = params->reduceTarget1In;
    resources[3].bufferTransient = params->reduceCouple1In;
    resources[4].bufferTransient = params->reduceWeight1In;
    resources[5].bufferTransient = params->key1In;
    resources[6].bufferTransient = params->scanTarget2In;
    resources[7].bufferTransient = params->scanCouple2In;
    resources[8].bufferTransient = params->scanWeight2In;
    resources[9].bufferTransient = params->key2In;
    resources[10].bufferTransient = params->scanTarget1Out;
    resources[11].bufferTransient = params->scanCouple1Out;
    resources[12].bufferTransient = params->scanWeight1Out;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 13; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterPointScan1CS";
    ptr->iface->addPassCompute(context, &pass);
}
