// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterPoint2CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterPoint2CS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterPoint2CS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterPoint2CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterPoint2CS_destroy(NvFlowContext* context, EmitterPoint2CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterPoint2CS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* gTable;
    NvFlowBufferTransient* arrayValuesIn;
    NvFlowBufferTransient* keyInOut;
    NvFlowBufferTransient* valInOut;
    NvFlowBufferTransient* keyLowInOut;
};
inline void EmitterPoint2CS_addPassCompute(NvFlowContext* context, EmitterPoint2CS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterPoint2CS_PassParams* params) {
    NvFlowDescriptorWrite writes[7] = {}; NvFlowResource resources[7] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[6].write.vulkan.binding = 6;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gSubStepParams;
    resources[2].bufferTransient = params->gTable;
    resources[3].bufferTransient = params->arrayValuesIn;
    resources[4].bufferTransient = params->keyInOut;
    resources[5].bufferTransient = params->valInOut;
    resources[6].bufferTransient = params->keyLowInOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 7; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterPoint2CS";
    ptr->iface->addPassCompute(context, &pass);
}
