// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterMeshTree1CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterMeshTree1CS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterMeshTree1CS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterMeshTree1CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterMeshTree1CS_destroy(NvFlowContext* context, EmitterMeshTree1CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterMeshTree1CS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* arrayValuesIn;
    NvFlowBufferTransient* sortKeyIn;
    NvFlowBufferTransient* sortValIn;
    NvFlowBufferTransient* bounds1Out;
    NvFlowBufferTransient* bounds2Out;
};
inline void EmitterMeshTree1CS_addPassCompute(NvFlowContext* context, EmitterMeshTree1CS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterMeshTree1CS_PassParams* params) {
    NvFlowDescriptorWrite writes[7] = {}; NvFlowResource resources[7] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[6].write.vulkan.binding = 6;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gSubStepParams;
    resources[2].bufferTransient = params->arrayValuesIn;
    resources[3].bufferTransient = params->sortKeyIn;
    resources[4].bufferTransient = params->sortValIn;
    resources[5].bufferTransient = params->bounds1Out;
    resources[6].bufferTransient = params->bounds2Out;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 7; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterMeshTree1CS";
    ptr->iface->addPassCompute(context, &pass);
}
