// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterNanoVdbCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterNanoVdbCS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterNanoVdbCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterNanoVdbCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterNanoVdbCS_destroy(NvFlowContext* context, EmitterNanoVdbCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterNanoVdbCS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gTable;
    NvFlowBufferTransient* arraysIn;
    NvFlowBufferTransient* interopDistances;
    NvFlowBufferTransient* interopVelocities;
    NvFlowBufferTransient* interopDivergences;
    NvFlowBufferTransient* interopTemperatures;
    NvFlowBufferTransient* interopFuels;
    NvFlowBufferTransient* interopBurns;
    NvFlowBufferTransient* interopSmokes;
    NvFlowTextureTransient* valueIn;
    NvFlowTextureTransient* valueOut;
    NvFlowTextureTransient* voxelWeightOut;
};
inline void EmitterNanoVdbCS_addPassCompute(NvFlowContext* context, EmitterNanoVdbCS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterNanoVdbCS_PassParams* params) {
    NvFlowDescriptorWrite writes[13] = {}; NvFlowResource resources[13] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_structuredBuffer; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_structuredBuffer; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_structuredBuffer; writes[8].write.vulkan.binding = 8;
    writes[9].type = eNvFlowDescriptorType_structuredBuffer; writes[9].write.vulkan.binding = 9;
    writes[10].type = eNvFlowDescriptorType_texture; writes[10].write.vulkan.binding = 10;
    writes[11].type = eNvFlowDescriptorType_rwTexture; writes[11].write.vulkan.binding = 11;
    writes[12].type = eNvFlowDescriptorType_rwTexture; writes[12].write.vulkan.binding = 12;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gTable;
    resources[2].bufferTransient = params->arraysIn;
    resources[3].bufferTransient = params->interopDistances;
    resources[4].bufferTransient = params->interopVelocities;
    resources[5].bufferTransient = params->interopDivergences;
    resources[6].bufferTransient = params->interopTemperatures;
    resources[7].bufferTransient = params->interopFuels;
    resources[8].bufferTransient = params->interopBurns;
    resources[9].bufferTransient = params->interopSmokes;
    resources[10].textureTransient = params->valueIn;
    resources[11].textureTransient = params->valueOut;
    resources[12].textureTransient = params->voxelWeightOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 13; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterNanoVdbCS";
    ptr->iface->addPassCompute(context, &pass);
}
