// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterBoxCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterBoxCS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterBoxCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterBoxCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterBoxCS_destroy(NvFlowContext* context, EmitterBoxCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterBoxCS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gInstanceParams;
    NvFlowBufferTransient* gPlanes;
    NvFlowBufferTransient* gPlaneCounts;
    NvFlowBufferTransient* gBlockIdx;
    NvFlowBufferTransient* gRange;
    NvFlowBufferTransient* gInstanceId;
    NvFlowBufferTransient* gTable;
    NvFlowTextureTransient* valueIn;
    NvFlowTextureTransient* valueOut;
};
inline void EmitterBoxCS_addPassCompute(NvFlowContext* context, EmitterBoxCS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterBoxCS_PassParams* params) {
    NvFlowDescriptorWrite writes[10] = {}; NvFlowResource resources[10] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_structuredBuffer; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_structuredBuffer; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_texture; writes[8].write.vulkan.binding = 8;
    writes[9].type = eNvFlowDescriptorType_rwTexture; writes[9].write.vulkan.binding = 9;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gInstanceParams;
    resources[2].bufferTransient = params->gPlanes;
    resources[3].bufferTransient = params->gPlaneCounts;
    resources[4].bufferTransient = params->gBlockIdx;
    resources[5].bufferTransient = params->gRange;
    resources[6].bufferTransient = params->gInstanceId;
    resources[7].bufferTransient = params->gTable;
    resources[8].textureTransient = params->valueIn;
    resources[9].textureTransient = params->valueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 10; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterBoxCS";
    ptr->iface->addPassCompute(context, &pass);
}
