// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterPoint1CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterPoint1CS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterPoint1CS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterPoint1CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterPoint1CS_destroy(NvFlowContext* context, EmitterPoint1CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterPoint1CS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* gTable;
    NvFlowBufferTransient* arrayValuesIn;
    NvFlowTextureTransient* valueIn;
    NvFlowBufferTransient* oldValueOut;
    NvFlowBufferTransient* keyOut;
    NvFlowBufferTransient* valOut;
    NvFlowBufferTransient* keyLowOut;
};
inline void EmitterPoint1CS_addPassCompute(NvFlowContext* context, EmitterPoint1CS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterPoint1CS_PassParams* params) {
    NvFlowDescriptorWrite writes[9] = {}; NvFlowResource resources[9] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_texture; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[8].write.vulkan.binding = 8;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gSubStepParams;
    resources[2].bufferTransient = params->gTable;
    resources[3].bufferTransient = params->arrayValuesIn;
    resources[4].textureTransient = params->valueIn;
    resources[5].bufferTransient = params->oldValueOut;
    resources[6].bufferTransient = params->keyOut;
    resources[7].bufferTransient = params->valOut;
    resources[8].bufferTransient = params->keyLowOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 9; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterPoint1CS";
    ptr->iface->addPassCompute(context, &pass);
}
