// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterPointReduce1CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterPointReduce1CS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterPointReduce1CS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterPointReduce1CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterPointReduce1CS_destroy(NvFlowContext* context, EmitterPointReduce1CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterPointReduce1CS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* gTable;
    NvFlowBufferTransient* arrayValuesIn;
    NvFlowBufferTransient* keyLowIn;
    NvFlowBufferTransient* keyIn;
    NvFlowBufferTransient* valIn;
    NvFlowBufferTransient* reduceTarget1Out;
    NvFlowBufferTransient* reduceCouple1Out;
    NvFlowBufferTransient* reduceWeight1Out;
    NvFlowBufferTransient* key1Out;
};
inline void EmitterPointReduce1CS_addPassCompute(NvFlowContext* context, EmitterPointReduce1CS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterPointReduce1CS_PassParams* params) {
    NvFlowDescriptorWrite writes[11] = {}; NvFlowResource resources[11] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_structuredBuffer; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[8].write.vulkan.binding = 8;
    writes[9].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[9].write.vulkan.binding = 9;
    writes[10].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[10].write.vulkan.binding = 10;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gSubStepParams;
    resources[2].bufferTransient = params->gTable;
    resources[3].bufferTransient = params->arrayValuesIn;
    resources[4].bufferTransient = params->keyLowIn;
    resources[5].bufferTransient = params->keyIn;
    resources[6].bufferTransient = params->valIn;
    resources[7].bufferTransient = params->reduceTarget1Out;
    resources[8].bufferTransient = params->reduceCouple1Out;
    resources[9].bufferTransient = params->reduceWeight1Out;
    resources[10].bufferTransient = params->key1Out;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 11; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterPointReduce1CS";
    ptr->iface->addPassCompute(context, &pass);
}
