// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterMeshApplyCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterMeshApplyCS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterMeshApplyCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterMeshApplyCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterMeshApplyCS_destroy(NvFlowContext* context, EmitterMeshApplyCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterMeshApplyCS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* gTable;
    NvFlowBufferTransient* arrayValuesIn;
    NvFlowTextureTransient* valueIn;
    NvFlowTextureTransient* closestIn;
    NvFlowTextureTransient* valueOut;
};
inline void EmitterMeshApplyCS_addPassCompute(NvFlowContext* context, EmitterMeshApplyCS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterMeshApplyCS_PassParams* params) {
    NvFlowDescriptorWrite writes[7] = {}; NvFlowResource resources[7] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_texture; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_texture; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_rwTexture; writes[6].write.vulkan.binding = 6;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gSubStepParams;
    resources[2].bufferTransient = params->gTable;
    resources[3].bufferTransient = params->arrayValuesIn;
    resources[4].textureTransient = params->valueIn;
    resources[5].textureTransient = params->closestIn;
    resources[6].textureTransient = params->valueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 7; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterMeshApplyCS";
    ptr->iface->addPassCompute(context, &pass);
}
