// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterMeshBounds2CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterMeshBounds2CS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterMeshBounds2CS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterMeshBounds2CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterMeshBounds2CS_destroy(NvFlowContext* context, EmitterMeshBounds2CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterMeshBounds2CS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* bounds2In;
    NvFlowBufferTransient* bounds3Out;
};
inline void EmitterMeshBounds2CS_addPassCompute(NvFlowContext* context, EmitterMeshBounds2CS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterMeshBounds2CS_PassParams* params) {
    NvFlowDescriptorWrite writes[3] = {}; NvFlowResource resources[3] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[2].write.vulkan.binding = 2;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->bounds2In;
    resources[2].bufferTransient = params->bounds3Out;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 3; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterMeshBounds2CS";
    ptr->iface->addPassCompute(context, &pass);
}
