// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterPointClearMarkedCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterPointClearMarkedCS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterPointClearMarkedCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterPointClearMarkedCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterPointClearMarkedCS_destroy(NvFlowContext* context, EmitterPointClearMarkedCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterPointClearMarkedCS_PassParams {
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowTextureTransient* voxelWeightIn;
    NvFlowTextureTransient* valueOut;
};
inline void EmitterPointClearMarkedCS_addPassCompute(NvFlowContext* context, EmitterPointClearMarkedCS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterPointClearMarkedCS_PassParams* params) {
    NvFlowDescriptorWrite writes[4] = {}; NvFlowResource resources[4] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_texture; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_rwTexture; writes[3].write.vulkan.binding = 3;
    resources[0].bufferTransient = params->globalParamsIn;
    resources[1].bufferTransient = params->tableIn;
    resources[2].textureTransient = params->voxelWeightIn;
    resources[3].textureTransient = params->valueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 4; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterPointClearMarkedCS";
    ptr->iface->addPassCompute(context, &pass);
}
