// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterTextureCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterTextureCS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterTextureCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterTextureCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterTextureCS_destroy(NvFlowContext* context, EmitterTextureCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterTextureCS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gTable;
    NvFlowBufferTransient* arrayValuesIn;
    NvFlowTextureTransient* valueIn;
    NvFlowTextureTransient* valueOut;
};
inline void EmitterTextureCS_addPassCompute(NvFlowContext* context, EmitterTextureCS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterTextureCS_PassParams* params) {
    NvFlowDescriptorWrite writes[5] = {}; NvFlowResource resources[5] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_texture; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_rwTexture; writes[4].write.vulkan.binding = 4;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gTable;
    resources[2].bufferTransient = params->arrayValuesIn;
    resources[3].textureTransient = params->valueIn;
    resources[4].textureTransient = params->valueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 5; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterTextureCS";
    ptr->iface->addPassCompute(context, &pass);
}
