// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterMeshClosestCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterMeshClosestCS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterMeshClosestCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterMeshClosestCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterMeshClosestCS_destroy(NvFlowContext* context, EmitterMeshClosestCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterMeshClosestCS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* gTable;
    NvFlowBufferTransient* arrayValuesIn;
    NvFlowBufferTransient* sortValIn;
    NvFlowBufferTransient* bounds1In;
    NvFlowBufferTransient* bounds2In;
    NvFlowBufferTransient* bounds3In;
    NvFlowBufferTransient* bounds4In;
    NvFlowTextureTransient* closestOut;
};
inline void EmitterMeshClosestCS_addPassCompute(NvFlowContext* context, EmitterMeshClosestCS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterMeshClosestCS_PassParams* params) {
    NvFlowDescriptorWrite writes[10] = {}; NvFlowResource resources[10] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_structuredBuffer; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_structuredBuffer; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_structuredBuffer; writes[8].write.vulkan.binding = 8;
    writes[9].type = eNvFlowDescriptorType_rwTexture; writes[9].write.vulkan.binding = 9;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gSubStepParams;
    resources[2].bufferTransient = params->gTable;
    resources[3].bufferTransient = params->arrayValuesIn;
    resources[4].bufferTransient = params->sortValIn;
    resources[5].bufferTransient = params->bounds1In;
    resources[6].bufferTransient = params->bounds2In;
    resources[7].bufferTransient = params->bounds3In;
    resources[8].bufferTransient = params->bounds4In;
    resources[9].textureTransient = params->closestOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 10; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterMeshClosestCS";
    ptr->iface->addPassCompute(context, &pass);
}
