// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterPointReduce2CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterPointReduce2CS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterPointReduce2CS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterPointReduce2CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterPointReduce2CS_destroy(NvFlowContext* context, EmitterPointReduce2CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterPointReduce2CS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* reduceTarget1In;
    NvFlowBufferTransient* reduceCouple1In;
    NvFlowBufferTransient* reduceWeight1In;
    NvFlowBufferTransient* key1In;
    NvFlowBufferTransient* reduceTarget2Out;
    NvFlowBufferTransient* reduceCouple2Out;
    NvFlowBufferTransient* reduceWeight2Out;
    NvFlowBufferTransient* key2Out;
};
inline void EmitterPointReduce2CS_addPassCompute(NvFlowContext* context, EmitterPointReduce2CS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterPointReduce2CS_PassParams* params) {
    NvFlowDescriptorWrite writes[10] = {}; NvFlowResource resources[10] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[8].write.vulkan.binding = 8;
    writes[9].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[9].write.vulkan.binding = 9;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gSubStepParams;
    resources[2].bufferTransient = params->reduceTarget1In;
    resources[3].bufferTransient = params->reduceCouple1In;
    resources[4].bufferTransient = params->reduceWeight1In;
    resources[5].bufferTransient = params->key1In;
    resources[6].bufferTransient = params->reduceTarget2Out;
    resources[7].bufferTransient = params->reduceCouple2Out;
    resources[8].bufferTransient = params->reduceWeight2Out;
    resources[9].bufferTransient = params->key2Out;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 10; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterPointReduce2CS";
    ptr->iface->addPassCompute(context, &pass);
}
