// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct EmitterMeshBounds1CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void EmitterMeshBounds1CS_init(NvFlowContextInterface* iface, NvFlowContext* context, EmitterMeshBounds1CS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/EmitterMeshBounds1CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void EmitterMeshBounds1CS_destroy(NvFlowContext* context, EmitterMeshBounds1CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct EmitterMeshBounds1CS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* arrayValuesIn;
    NvFlowBufferTransient* bounds2Out;
};
inline void EmitterMeshBounds1CS_addPassCompute(NvFlowContext* context, EmitterMeshBounds1CS_Pipeline* ptr, NvFlowUint3 gridDim, const EmitterMeshBounds1CS_PassParams* params) {
    NvFlowDescriptorWrite writes[4] = {}; NvFlowResource resources[4] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[3].write.vulkan.binding = 3;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gSubStepParams;
    resources[2].bufferTransient = params->arrayValuesIn;
    resources[3].bufferTransient = params->bounds2Out;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 4; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "EmitterMeshBounds1CS";
    ptr->iface->addPassCompute(context, &pass);
}
