// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct ImguiTileScanCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void ImguiTileScanCS_init(NvFlowContextInterface* iface, NvFlowContext* context, ImguiTileScanCS_Pipeline* ptr) {
    static const char token[] = "source/nvfloweditor/shaders/ImguiTileScanCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void ImguiTileScanCS_destroy(NvFlowContext* context, ImguiTileScanCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct ImguiTileScanCS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* tileCountOut;
    NvFlowBufferTransient* totalCountOut;
};
inline void ImguiTileScanCS_addPassCompute(NvFlowContext* context, ImguiTileScanCS_Pipeline* ptr, NvFlowUint3 gridDim, const ImguiTileScanCS_PassParams* params) {
    NvFlowDescriptorWrite writes[3] = {}; NvFlowResource resources[3] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[2].write.vulkan.binding = 2;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->tileCountOut;
    resources[2].bufferTransient = params->totalCountOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 3; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "ImguiTileScanCS";
    ptr->iface->addPassCompute(context, &pass);
}
