// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct ImguiCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void ImguiCS_init(NvFlowContextInterface* iface, NvFlowContext* context, ImguiCS_Pipeline* ptr) {
    static const char token[] = "source/nvfloweditor/shaders/ImguiCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void ImguiCS_destroy(NvFlowContext* context, ImguiCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct ImguiCS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* vertexPosTexCoordIn;
    NvFlowBufferTransient* vertexColorIn;
    NvFlowBufferTransient* indicesIn;
    NvFlowBufferTransient* drawCmdsIn;
    NvFlowBufferTransient* textureTableIn;
    NvFlowTextureTransient* textureIn;
    NvFlowSampler* samplerIn;
    NvFlowBufferTransient* triangleIn;
    NvFlowBufferTransient* triangleRangeIn;
    NvFlowTextureTransient* colorIn;
    NvFlowTextureTransient* colorOut;
};
inline void ImguiCS_addPassCompute(NvFlowContext* context, ImguiCS_Pipeline* ptr, NvFlowUint3 gridDim, const ImguiCS_PassParams* params) {
    NvFlowDescriptorWrite writes[12] = {}; NvFlowResource resources[12] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_texture; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_sampler; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_structuredBuffer; writes[8].write.vulkan.binding = 8;
    writes[9].type = eNvFlowDescriptorType_structuredBuffer; writes[9].write.vulkan.binding = 9;
    writes[10].type = eNvFlowDescriptorType_texture; writes[10].write.vulkan.binding = 10;
    writes[11].type = eNvFlowDescriptorType_rwTexture; writes[11].write.vulkan.binding = 11;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->vertexPosTexCoordIn;
    resources[2].bufferTransient = params->vertexColorIn;
    resources[3].bufferTransient = params->indicesIn;
    resources[4].bufferTransient = params->drawCmdsIn;
    resources[5].bufferTransient = params->textureTableIn;
    resources[6].textureTransient = params->textureIn;
    resources[7].sampler = params->samplerIn;
    resources[8].bufferTransient = params->triangleIn;
    resources[9].bufferTransient = params->triangleRangeIn;
    resources[10].textureTransient = params->colorIn;
    resources[11].textureTransient = params->colorOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 12; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "ImguiCS";
    ptr->iface->addPassCompute(context, &pass);
}
