// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct ImguiTileCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void ImguiTileCS_init(NvFlowContextInterface* iface, NvFlowContext* context, ImguiTileCS_Pipeline* ptr) {
    static const char token[] = "source/nvfloweditor/shaders/ImguiTileCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void ImguiTileCS_destroy(NvFlowContext* context, ImguiTileCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct ImguiTileCS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* treeIn;
    NvFlowBufferTransient* tileCountIn;
    NvFlowBufferTransient* drawCmdsIn;
    NvFlowBufferTransient* triangleOut;
    NvFlowBufferTransient* triangleRangeOut;
};
inline void ImguiTileCS_addPassCompute(NvFlowContext* context, ImguiTileCS_Pipeline* ptr, NvFlowUint3 gridDim, const ImguiTileCS_PassParams* params) {
    NvFlowDescriptorWrite writes[6] = {}; NvFlowResource resources[6] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[5].write.vulkan.binding = 5;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->treeIn;
    resources[2].bufferTransient = params->tileCountIn;
    resources[3].bufferTransient = params->drawCmdsIn;
    resources[4].bufferTransient = params->triangleOut;
    resources[5].bufferTransient = params->triangleRangeOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 6; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "ImguiTileCS";
    ptr->iface->addPassCompute(context, &pass);
}
