// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct ImguiBuildCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void ImguiBuildCS_init(NvFlowContextInterface* iface, NvFlowContext* context, ImguiBuildCS_Pipeline* ptr) {
    static const char token[] = "source/nvfloweditor/shaders/ImguiBuildCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void ImguiBuildCS_destroy(NvFlowContext* context, ImguiBuildCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct ImguiBuildCS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* vertexPosTexCoordIn;
    NvFlowBufferTransient* vertexColorIn;
    NvFlowBufferTransient* indicesIn;
    NvFlowBufferTransient* drawCmdsIn;
    NvFlowBufferTransient* treeOut;
};
inline void ImguiBuildCS_addPassCompute(NvFlowContext* context, ImguiBuildCS_Pipeline* ptr, NvFlowUint3 gridDim, const ImguiBuildCS_PassParams* params) {
    NvFlowDescriptorWrite writes[6] = {}; NvFlowResource resources[6] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[5].write.vulkan.binding = 5;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->vertexPosTexCoordIn;
    resources[2].bufferTransient = params->vertexColorIn;
    resources[3].bufferTransient = params->indicesIn;
    resources[4].bufferTransient = params->drawCmdsIn;
    resources[5].bufferTransient = params->treeOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 6; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "ImguiBuildCS";
    ptr->iface->addPassCompute(context, &pass);
}
