// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct ImguiTextureUploadCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void ImguiTextureUploadCS_init(NvFlowContextInterface* iface, NvFlowContext* context, ImguiTextureUploadCS_Pipeline* ptr) {
    static const char token[] = "source/nvfloweditor/shaders/ImguiTextureUploadCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void ImguiTextureUploadCS_destroy(NvFlowContext* context, ImguiTextureUploadCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct ImguiTextureUploadCS_PassParams {
    NvFlowBufferTransient* uploadIn;
    NvFlowTextureTransient* colorOut;
};
inline void ImguiTextureUploadCS_addPassCompute(NvFlowContext* context, ImguiTextureUploadCS_Pipeline* ptr, NvFlowUint3 gridDim, const ImguiTextureUploadCS_PassParams* params) {
    NvFlowDescriptorWrite writes[2] = {}; NvFlowResource resources[2] = {};
    writes[0].type = eNvFlowDescriptorType_structuredBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_rwTexture; writes[1].write.vulkan.binding = 1;
    resources[0].bufferTransient = params->uploadIn;
    resources[1].textureTransient = params->colorOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 2; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "ImguiTextureUploadCS";
    ptr->iface->addPassCompute(context, &pass);
}
