// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct PressureSubtractCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void PressureSubtractCS_init(NvFlowContextInterface* iface, NvFlowContext* context, PressureSubtractCS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/PressureSubtractCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void PressureSubtractCS_destroy(NvFlowContext* context, PressureSubtractCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct PressureSubtractCS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gTable;
    NvFlowTextureTransient* pressureIn;
    NvFlowTextureTransient* velocityIn;
    NvFlowTextureTransient* velocityOut;
};
inline void PressureSubtractCS_addPassCompute(NvFlowContext* context, PressureSubtractCS_Pipeline* ptr, NvFlowUint3 gridDim, const PressureSubtractCS_PassParams* params) {
    NvFlowDescriptorWrite writes[5] = {}; NvFlowResource resources[5] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_texture; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_texture; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_rwTexture; writes[4].write.vulkan.binding = 4;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gTable;
    resources[2].textureTransient = params->pressureIn;
    resources[3].textureTransient = params->velocityIn;
    resources[4].textureTransient = params->velocityOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 5; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "PressureSubtractCS";
    ptr->iface->addPassCompute(context, &pass);
}
