// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct PressureRestrictCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void PressureRestrictCS_init(NvFlowContextInterface* iface, NvFlowContext* context, PressureRestrictCS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/PressureRestrictCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void PressureRestrictCS_destroy(NvFlowContext* context, PressureRestrictCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct PressureRestrictCS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gTable;
    NvFlowTextureTransient* residualIn;
    NvFlowSampler* valueSampler;
    NvFlowTextureTransient* pressureOut;
};
inline void PressureRestrictCS_addPassCompute(NvFlowContext* context, PressureRestrictCS_Pipeline* ptr, NvFlowUint3 gridDim, const PressureRestrictCS_PassParams* params) {
    NvFlowDescriptorWrite writes[5] = {}; NvFlowResource resources[5] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_texture; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_sampler; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_rwTexture; writes[4].write.vulkan.binding = 4;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gTable;
    resources[2].textureTransient = params->residualIn;
    resources[3].sampler = params->valueSampler;
    resources[4].textureTransient = params->pressureOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 5; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "PressureRestrictCS";
    ptr->iface->addPassCompute(context, &pass);
}
