// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct PressureJacobiCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void PressureJacobiCS_init(NvFlowContextInterface* iface, NvFlowContext* context, PressureJacobiCS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/PressureJacobiCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void PressureJacobiCS_destroy(NvFlowContext* context, PressureJacobiCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct PressureJacobiCS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gTable;
    NvFlowTextureTransient* pressureIn;
    NvFlowTextureTransient* pressureOut;
};
inline void PressureJacobiCS_addPassCompute(NvFlowContext* context, PressureJacobiCS_Pipeline* ptr, NvFlowUint3 gridDim, const PressureJacobiCS_PassParams* params) {
    NvFlowDescriptorWrite writes[4] = {}; NvFlowResource resources[4] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_texture; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_rwTexture; writes[3].write.vulkan.binding = 3;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gTable;
    resources[2].textureTransient = params->pressureIn;
    resources[3].textureTransient = params->pressureOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 4; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "PressureJacobiCS";
    ptr->iface->addPassCompute(context, &pass);
}
