// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct PrMomentumGatherCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void PrMomentumGatherCS_init(NvFlowContextInterface* iface, NvFlowContext* context, PrMomentumGatherCS_Pipeline* ptr) {
    static const char token[] = "addons/momentum/PrMomentumGatherCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void PrMomentumGatherCS_destroy(NvFlowContext* context, PrMomentumGatherCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct PrMomentumGatherCS_PassParams {
    NvFlowBufferTransient* prBoundary;
    NvFlowBufferTransient* prBoundaryControl;
    NvFlowBufferTransient* params;
    NvFlowBufferTransient* table;
    NvFlowTextureTransient* velocity;
    NvFlowBufferTransient* contacts;
    NvFlowBufferTransient* counts;
};
inline void PrMomentumGatherCS_addPassCompute(NvFlowContext* context, PrMomentumGatherCS_Pipeline* ptr, NvFlowUint3 gridDim, const PrMomentumGatherCS_PassParams* params) {
    NvFlowDescriptorWrite writes[7] = {}; NvFlowResource resources[7] = {};
    writes[0].type = eNvFlowDescriptorType_structuredBuffer; writes[0].write.vulkan.binding = 30;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 31;
    writes[2].type = eNvFlowDescriptorType_constantBuffer; writes[2].write.vulkan.binding = 0;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 1;
    writes[4].type = eNvFlowDescriptorType_texture; writes[4].write.vulkan.binding = 2;
    writes[5].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[5].write.vulkan.binding = 3;
    writes[6].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[6].write.vulkan.binding = 4;
    resources[0].bufferTransient = params->prBoundary;
    resources[1].bufferTransient = params->prBoundaryControl;
    resources[2].bufferTransient = params->params;
    resources[3].bufferTransient = params->table;
    resources[4].textureTransient = params->velocity;
    resources[5].bufferTransient = params->contacts;
    resources[6].bufferTransient = params->counts;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 7; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "PrMomentumGatherCS";
    ptr->iface->addPassCompute(context, &pass);
}
