// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct PrMomentumApplyCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void PrMomentumApplyCS_init(NvFlowContextInterface* iface, NvFlowContext* context, PrMomentumApplyCS_Pipeline* ptr) {
    static const char token[] = "addons/momentum/PrMomentumApplyCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void PrMomentumApplyCS_destroy(NvFlowContext* context, PrMomentumApplyCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct PrMomentumApplyCS_PassParams {
    NvFlowBufferTransient* params;
    NvFlowBufferTransient* table;
    NvFlowBufferTransient* updates;
    NvFlowTextureTransient* velocity;
};
inline void PrMomentumApplyCS_addPassCompute(NvFlowContext* context, PrMomentumApplyCS_Pipeline* ptr, NvFlowUint3 gridDim, const PrMomentumApplyCS_PassParams* params) {
    NvFlowDescriptorWrite writes[4] = {}; NvFlowResource resources[4] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_rwTexture; writes[3].write.vulkan.binding = 3;
    resources[0].bufferTransient = params->params;
    resources[1].bufferTransient = params->table;
    resources[2].bufferTransient = params->updates;
    resources[3].textureTransient = params->velocity;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 4; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "PrMomentumApplyCS";
    ptr->iface->addPassCompute(context, &pass);
}
