// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct PrScalarCountCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void PrScalarCountCS_init(NvFlowContextInterface* iface, NvFlowContext* context, PrScalarCountCS_Pipeline* ptr) {
    static const char token[] = "addons/scalar/PrScalarCountCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void PrScalarCountCS_destroy(NvFlowContext* context, PrScalarCountCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct PrScalarCountCS_PassParams {
    NvFlowBufferTransient* scalarParams;
    NvFlowBufferTransient* scalarAdmission;
    NvFlowBufferTransient* scalarCounts;
};
inline void PrScalarCountCS_addPassCompute(NvFlowContext* context, PrScalarCountCS_Pipeline* ptr, NvFlowUint3 gridDim, const PrScalarCountCS_PassParams* params) {
    NvFlowDescriptorWrite writes[3] = {}; NvFlowResource resources[3] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[2].write.vulkan.binding = 2;
    resources[0].bufferTransient = params->scalarParams;
    resources[1].bufferTransient = params->scalarAdmission;
    resources[2].bufferTransient = params->scalarCounts;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 3; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "PrScalarCountCS";
    ptr->iface->addPassCompute(context, &pass);
}
