// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct PrScalarReceiptCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void PrScalarReceiptCS_init(NvFlowContextInterface* iface, NvFlowContext* context, PrScalarReceiptCS_Pipeline* ptr) {
    static const char token[] = "addons/scalar/PrScalarReceiptCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void PrScalarReceiptCS_destroy(NvFlowContext* context, PrScalarReceiptCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct PrScalarReceiptCS_PassParams {
    NvFlowBufferTransient* scalarParams;
    NvFlowBufferTransient* scalarSources;
    NvFlowBufferTransient* scalarSamples;
    NvFlowBufferTransient* scalarAdmission;
    NvFlowBufferTransient* scalarCounts;
    NvFlowBufferTransient* scalarRatios;
    NvFlowBufferTransient* scalarReceipts;
};
inline void PrScalarReceiptCS_addPassCompute(NvFlowContext* context, PrScalarReceiptCS_Pipeline* ptr, NvFlowUint3 gridDim, const PrScalarReceiptCS_PassParams* params) {
    NvFlowDescriptorWrite writes[7] = {}; NvFlowResource resources[7] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[6].write.vulkan.binding = 6;
    resources[0].bufferTransient = params->scalarParams;
    resources[1].bufferTransient = params->scalarSources;
    resources[2].bufferTransient = params->scalarSamples;
    resources[3].bufferTransient = params->scalarAdmission;
    resources[4].bufferTransient = params->scalarCounts;
    resources[5].bufferTransient = params->scalarRatios;
    resources[6].bufferTransient = params->scalarReceipts;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 7; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "PrScalarReceiptCS";
    ptr->iface->addPassCompute(context, &pass);
}
