// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct PrScalarAdmitCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void PrScalarAdmitCS_init(NvFlowContextInterface* iface, NvFlowContext* context, PrScalarAdmitCS_Pipeline* ptr) {
    static const char token[] = "addons/scalar/PrScalarAdmitCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void PrScalarAdmitCS_destroy(NvFlowContext* context, PrScalarAdmitCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct PrScalarAdmitCS_PassParams {
    NvFlowBufferTransient* prBoundary;
    NvFlowBufferTransient* prBoundaryControl;
    NvFlowBufferTransient* scalarParams;
    NvFlowBufferTransient* scalarSamples;
    NvFlowBufferTransient* scalarTable;
    NvFlowBufferTransient* scalarAdmission;
};
inline void PrScalarAdmitCS_addPassCompute(NvFlowContext* context, PrScalarAdmitCS_Pipeline* ptr, NvFlowUint3 gridDim, const PrScalarAdmitCS_PassParams* params) {
    NvFlowDescriptorWrite writes[6] = {}; NvFlowResource resources[6] = {};
    writes[0].type = eNvFlowDescriptorType_structuredBuffer; writes[0].write.vulkan.binding = 30;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 31;
    writes[2].type = eNvFlowDescriptorType_constantBuffer; writes[2].write.vulkan.binding = 0;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 1;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 2;
    writes[5].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[5].write.vulkan.binding = 3;
    resources[0].bufferTransient = params->prBoundary;
    resources[1].bufferTransient = params->prBoundaryControl;
    resources[2].bufferTransient = params->scalarParams;
    resources[3].bufferTransient = params->scalarSamples;
    resources[4].bufferTransient = params->scalarTable;
    resources[5].bufferTransient = params->scalarAdmission;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 6; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "PrScalarAdmitCS";
    ptr->iface->addPassCompute(context, &pass);
}
