// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct PrScalarApplyCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void PrScalarApplyCS_init(NvFlowContextInterface* iface, NvFlowContext* context, PrScalarApplyCS_Pipeline* ptr) {
    static const char token[] = "addons/scalar/PrScalarApplyCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void PrScalarApplyCS_destroy(NvFlowContext* context, PrScalarApplyCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct PrScalarApplyCS_PassParams {
    NvFlowBufferTransient* scalarParams;
    NvFlowBufferTransient* scalarSources;
    NvFlowBufferTransient* scalarCells;
    NvFlowBufferTransient* scalarMembers;
    NvFlowBufferTransient* scalarAdmission;
    NvFlowBufferTransient* scalarCounts;
    NvFlowTextureTransient* scalarDensityIn;
    NvFlowTextureTransient* scalarDensityOut;
    NvFlowBufferTransient* scalarRatios;
};
inline void PrScalarApplyCS_addPassCompute(NvFlowContext* context, PrScalarApplyCS_Pipeline* ptr, NvFlowUint3 gridDim, const PrScalarApplyCS_PassParams* params) {
    NvFlowDescriptorWrite writes[9] = {}; NvFlowResource resources[9] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_texture; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_rwTexture; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[8].write.vulkan.binding = 8;
    resources[0].bufferTransient = params->scalarParams;
    resources[1].bufferTransient = params->scalarSources;
    resources[2].bufferTransient = params->scalarCells;
    resources[3].bufferTransient = params->scalarMembers;
    resources[4].bufferTransient = params->scalarAdmission;
    resources[5].bufferTransient = params->scalarCounts;
    resources[6].textureTransient = params->scalarDensityIn;
    resources[7].textureTransient = params->scalarDensityOut;
    resources[8].bufferTransient = params->scalarRatios;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 9; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "PrScalarApplyCS";
    ptr->iface->addPassCompute(context, &pass);
}
