// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct RadixSortPadCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void RadixSortPadCS_init(NvFlowContextInterface* iface, NvFlowContext* context, RadixSortPadCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/RadixSortPadCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void RadixSortPadCS_destroy(NvFlowContext* context, RadixSortPadCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct RadixSortPadCS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* keyDst;
};
inline void RadixSortPadCS_addPassCompute(NvFlowContext* context, RadixSortPadCS_Pipeline* ptr, NvFlowUint3 gridDim, const RadixSortPadCS_PassParams* params) {
    NvFlowDescriptorWrite writes[2] = {}; NvFlowResource resources[2] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[1].write.vulkan.binding = 1;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->keyDst;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 2; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "RadixSortPadCS";
    ptr->iface->addPassCompute(context, &pass);
}
