// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct RadixSortBlockCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void RadixSortBlockCS_init(NvFlowContextInterface* iface, NvFlowContext* context, RadixSortBlockCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/RadixSortBlockCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void RadixSortBlockCS_destroy(NvFlowContext* context, RadixSortBlockCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct RadixSortBlockCS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* keyIn;
    NvFlowBufferTransient* valIn;
    NvFlowBufferTransient* keyOut;
    NvFlowBufferTransient* valOut;
};
inline void RadixSortBlockCS_addPassCompute(NvFlowContext* context, RadixSortBlockCS_Pipeline* ptr, NvFlowUint3 gridDim, const RadixSortBlockCS_PassParams* params) {
    NvFlowDescriptorWrite writes[5] = {}; NvFlowResource resources[5] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[4].write.vulkan.binding = 4;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->keyIn;
    resources[2].bufferTransient = params->valIn;
    resources[3].bufferTransient = params->keyOut;
    resources[4].bufferTransient = params->valOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 5; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "RadixSortBlockCS";
    ptr->iface->addPassCompute(context, &pass);
}
