// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct RadixSort3CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void RadixSort3CS_init(NvFlowContextInterface* iface, NvFlowContext* context, RadixSort3CS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/RadixSort3CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void RadixSort3CS_destroy(NvFlowContext* context, RadixSort3CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct RadixSort3CS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* keyIn;
    NvFlowBufferTransient* valIn;
    NvFlowBufferTransient* countersIn;
    NvFlowBufferTransient* keyOut;
    NvFlowBufferTransient* valOut;
};
inline void RadixSort3CS_addPassCompute(NvFlowContext* context, RadixSort3CS_Pipeline* ptr, NvFlowUint3 gridDim, const RadixSort3CS_PassParams* params) {
    NvFlowDescriptorWrite writes[6] = {}; NvFlowResource resources[6] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[5].write.vulkan.binding = 5;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->keyIn;
    resources[2].bufferTransient = params->valIn;
    resources[3].bufferTransient = params->countersIn;
    resources[4].bufferTransient = params->keyOut;
    resources[5].bufferTransient = params->valOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 6; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "RadixSort3CS";
    ptr->iface->addPassCompute(context, &pass);
}
