// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct RadixSort1CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void RadixSort1CS_init(NvFlowContextInterface* iface, NvFlowContext* context, RadixSort1CS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/RadixSort1CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void RadixSort1CS_destroy(NvFlowContext* context, RadixSort1CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct RadixSort1CS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* keyIn;
    NvFlowBufferTransient* countersOut;
};
inline void RadixSort1CS_addPassCompute(NvFlowContext* context, RadixSort1CS_Pipeline* ptr, NvFlowUint3 gridDim, const RadixSort1CS_PassParams* params) {
    NvFlowDescriptorWrite writes[3] = {}; NvFlowResource resources[3] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[2].write.vulkan.binding = 2;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->keyIn;
    resources[2].bufferTransient = params->countersOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 3; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "RadixSort1CS";
    ptr->iface->addPassCompute(context, &pass);
}
