// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct RayMarchUpdateColormapCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void RayMarchUpdateColormapCS_init(NvFlowContextInterface* iface, NvFlowContext* context, RayMarchUpdateColormapCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/RayMarchUpdateColormapCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void RayMarchUpdateColormapCS_destroy(NvFlowContext* context, RayMarchUpdateColormapCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct RayMarchUpdateColormapCS_PassParams {
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* layerParamsIn;
    NvFlowBufferTransient* pointParamsIn;
    NvFlowTextureTransient* gColormapOut;
};
inline void RayMarchUpdateColormapCS_addPassCompute(NvFlowContext* context, RayMarchUpdateColormapCS_Pipeline* ptr, NvFlowUint3 gridDim, const RayMarchUpdateColormapCS_PassParams* params) {
    NvFlowDescriptorWrite writes[4] = {}; NvFlowResource resources[4] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_rwTexture; writes[3].write.vulkan.binding = 3;
    resources[0].bufferTransient = params->globalParamsIn;
    resources[1].bufferTransient = params->layerParamsIn;
    resources[2].bufferTransient = params->pointParamsIn;
    resources[3].textureTransient = params->gColormapOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 4; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "RayMarchUpdateColormapCS";
    ptr->iface->addPassCompute(context, &pass);
}
