// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct RayMarchBlockIsosurfaceCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void RayMarchBlockIsosurfaceCS_init(NvFlowContextInterface* iface, NvFlowContext* context, RayMarchBlockIsosurfaceCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/RayMarchBlockIsosurfaceCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void RayMarchBlockIsosurfaceCS_destroy(NvFlowContext* context, RayMarchBlockIsosurfaceCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct RayMarchBlockIsosurfaceCS_PassParams {
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* layerParamsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowTextureTransient* densityIn;
    NvFlowSampler* densitySampler;
    NvFlowTextureTransient* depthIn;
    NvFlowTextureTransient* colorIn;
    NvFlowTextureTransient* colorOut;
};
inline void RayMarchBlockIsosurfaceCS_addPassCompute(NvFlowContext* context, RayMarchBlockIsosurfaceCS_Pipeline* ptr, NvFlowUint3 gridDim, const RayMarchBlockIsosurfaceCS_PassParams* params) {
    NvFlowDescriptorWrite writes[8] = {}; NvFlowResource resources[8] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_texture; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_sampler; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_texture; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_texture; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_rwTexture; writes[7].write.vulkan.binding = 7;
    resources[0].bufferTransient = params->globalParamsIn;
    resources[1].bufferTransient = params->layerParamsIn;
    resources[2].bufferTransient = params->tableIn;
    resources[3].textureTransient = params->densityIn;
    resources[4].sampler = params->densitySampler;
    resources[5].textureTransient = params->depthIn;
    resources[6].textureTransient = params->colorIn;
    resources[7].textureTransient = params->colorOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 8; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "RayMarchBlockIsosurfaceCS";
    ptr->iface->addPassCompute(context, &pass);
}
