// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct RayMarchCopyTextureCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void RayMarchCopyTextureCS_init(NvFlowContextInterface* iface, NvFlowContext* context, RayMarchCopyTextureCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/RayMarchCopyTextureCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void RayMarchCopyTextureCS_destroy(NvFlowContext* context, RayMarchCopyTextureCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct RayMarchCopyTextureCS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowTextureTransient* colorIn;
    NvFlowTextureTransient* colorOut;
};
inline void RayMarchCopyTextureCS_addPassCompute(NvFlowContext* context, RayMarchCopyTextureCS_Pipeline* ptr, NvFlowUint3 gridDim, const RayMarchCopyTextureCS_PassParams* params) {
    NvFlowDescriptorWrite writes[3] = {}; NvFlowResource resources[3] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_texture; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_rwTexture; writes[2].write.vulkan.binding = 2;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].textureTransient = params->colorIn;
    resources[2].textureTransient = params->colorOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 3; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "RayMarchCopyTextureCS";
    ptr->iface->addPassCompute(context, &pass);
}
