// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct RayMarchBlockCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void RayMarchBlockCS_init(NvFlowContextInterface* iface, NvFlowContext* context, RayMarchBlockCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/RayMarchBlockCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void RayMarchBlockCS_destroy(NvFlowContext* context, RayMarchBlockCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct RayMarchBlockCS_PassParams {
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* layerParamsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowTextureTransient* velocityIn;
    NvFlowSampler* velocitySampler;
    NvFlowTextureTransient* densityIn;
    NvFlowSampler* densitySampler;
    NvFlowTextureTransient* colormapIn;
    NvFlowSampler* colormapSampler;
    NvFlowTextureTransient* depthIn;
    NvFlowTextureTransient* colorIn;
    NvFlowTextureTransient* colorOut;
};
inline void RayMarchBlockCS_addPassCompute(NvFlowContext* context, RayMarchBlockCS_Pipeline* ptr, NvFlowUint3 gridDim, const RayMarchBlockCS_PassParams* params) {
    NvFlowDescriptorWrite writes[12] = {}; NvFlowResource resources[12] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_texture; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_sampler; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_texture; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_sampler; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_texture; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_sampler; writes[8].write.vulkan.binding = 8;
    writes[9].type = eNvFlowDescriptorType_texture; writes[9].write.vulkan.binding = 9;
    writes[10].type = eNvFlowDescriptorType_texture; writes[10].write.vulkan.binding = 10;
    writes[11].type = eNvFlowDescriptorType_rwTexture; writes[11].write.vulkan.binding = 11;
    resources[0].bufferTransient = params->globalParamsIn;
    resources[1].bufferTransient = params->layerParamsIn;
    resources[2].bufferTransient = params->tableIn;
    resources[3].textureTransient = params->velocityIn;
    resources[4].sampler = params->velocitySampler;
    resources[5].textureTransient = params->densityIn;
    resources[6].sampler = params->densitySampler;
    resources[7].textureTransient = params->colormapIn;
    resources[8].sampler = params->colormapSampler;
    resources[9].textureTransient = params->depthIn;
    resources[10].textureTransient = params->colorIn;
    resources[11].textureTransient = params->colorOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 12; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "RayMarchBlockCS";
    ptr->iface->addPassCompute(context, &pass);
}
