// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct ShadowNullCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void ShadowNullCS_init(NvFlowContextInterface* iface, NvFlowContext* context, ShadowNullCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/ShadowNullCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void ShadowNullCS_destroy(NvFlowContext* context, ShadowNullCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct ShadowNullCS_PassParams {
    NvFlowTextureTransient* valueOut;
};
inline void ShadowNullCS_addPassCompute(NvFlowContext* context, ShadowNullCS_Pipeline* ptr, NvFlowUint3 gridDim, const ShadowNullCS_PassParams* params) {
    NvFlowDescriptorWrite writes[1] = {}; NvFlowResource resources[1] = {};
    writes[0].type = eNvFlowDescriptorType_rwTexture; writes[0].write.vulkan.binding = 0;
    resources[0].textureTransient = params->valueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 1; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "ShadowNullCS";
    ptr->iface->addPassCompute(context, &pass);
}
