// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct ShadowUpdateCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void ShadowUpdateCS_init(NvFlowContextInterface* iface, NvFlowContext* context, ShadowUpdateCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/ShadowUpdateCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void ShadowUpdateCS_destroy(NvFlowContext* context, ShadowUpdateCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct ShadowUpdateCS_PassParams {
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* layerParamsIn;
    NvFlowBufferTransient* gTable;
    NvFlowTextureTransient* gInput;
    NvFlowSampler* gSampler;
    NvFlowTextureTransient* gColormap;
    NvFlowSampler* gColormapSampler;
    NvFlowTextureTransient* densityOut;
};
inline void ShadowUpdateCS_addPassCompute(NvFlowContext* context, ShadowUpdateCS_Pipeline* ptr, NvFlowUint3 gridDim, const ShadowUpdateCS_PassParams* params) {
    NvFlowDescriptorWrite writes[8] = {}; NvFlowResource resources[8] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_texture; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_sampler; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_texture; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_sampler; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_rwTexture; writes[7].write.vulkan.binding = 7;
    resources[0].bufferTransient = params->globalParamsIn;
    resources[1].bufferTransient = params->layerParamsIn;
    resources[2].bufferTransient = params->gTable;
    resources[3].textureTransient = params->gInput;
    resources[4].sampler = params->gSampler;
    resources[5].textureTransient = params->gColormap;
    resources[6].sampler = params->gColormapSampler;
    resources[7].textureTransient = params->densityOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 8; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "ShadowUpdateCS";
    ptr->iface->addPassCompute(context, &pass);
}
