// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct ShapeCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void ShapeCS_init(NvFlowContextInterface* iface, NvFlowContext* context, ShapeCS_Pipeline* ptr) {
    static const char token[] = "source/nvfloweditor/shaders/ShapeCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void ShapeCS_destroy(NvFlowContext* context, ShapeCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct ShapeCS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* spherePositionRadiusIn;
    NvFlowTextureTransient* depthOut;
    NvFlowTextureTransient* colorOut;
};
inline void ShapeCS_addPassCompute(NvFlowContext* context, ShapeCS_Pipeline* ptr, NvFlowUint3 gridDim, const ShapeCS_PassParams* params) {
    NvFlowDescriptorWrite writes[4] = {}; NvFlowResource resources[4] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_rwTexture; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_rwTexture; writes[3].write.vulkan.binding = 3;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->spherePositionRadiusIn;
    resources[2].textureTransient = params->depthOut;
    resources[3].textureTransient = params->colorOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 4; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "ShapeCS";
    ptr->iface->addPassCompute(context, &pass);
}
