// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SolidEmitterSimpleCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SolidEmitterSimpleCS_init(NvFlowContextInterface* iface, NvFlowContext* context, SolidEmitterSimpleCS_Pipeline* ptr) {
    static const char token[] = "addons/solid/SolidEmitterSimpleCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SolidEmitterSimpleCS_destroy(NvFlowContext* context, SolidEmitterSimpleCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SolidEmitterSimpleCS_PassParams {
    NvFlowBufferTransient* prBoundary;
    NvFlowBufferTransient* prBoundaryControl;
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gTable;
    NvFlowTextureTransient* valueIn;
    NvFlowTextureTransient* velocityIn;
    NvFlowSampler* samplerIn;
    NvFlowTextureTransient* valueOut;
};
inline void SolidEmitterSimpleCS_addPassCompute(NvFlowContext* context, SolidEmitterSimpleCS_Pipeline* ptr, NvFlowUint3 gridDim, const SolidEmitterSimpleCS_PassParams* params) {
    NvFlowDescriptorWrite writes[8] = {}; NvFlowResource resources[8] = {};
    writes[0].type = eNvFlowDescriptorType_structuredBuffer; writes[0].write.vulkan.binding = 30;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 31;
    writes[2].type = eNvFlowDescriptorType_constantBuffer; writes[2].write.vulkan.binding = 0;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 1;
    writes[4].type = eNvFlowDescriptorType_texture; writes[4].write.vulkan.binding = 2;
    writes[5].type = eNvFlowDescriptorType_texture; writes[5].write.vulkan.binding = 3;
    writes[6].type = eNvFlowDescriptorType_sampler; writes[6].write.vulkan.binding = 4;
    writes[7].type = eNvFlowDescriptorType_rwTexture; writes[7].write.vulkan.binding = 5;
    resources[0].bufferTransient = params->prBoundary;
    resources[1].bufferTransient = params->prBoundaryControl;
    resources[2].bufferTransient = params->gParams;
    resources[3].bufferTransient = params->gTable;
    resources[4].textureTransient = params->valueIn;
    resources[5].textureTransient = params->velocityIn;
    resources[6].sampler = params->samplerIn;
    resources[7].textureTransient = params->valueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 8; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SolidEmitterSimpleCS";
    ptr->iface->addPassCompute(context, &pass);
}
