// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SolidEmitterPoint4CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SolidEmitterPoint4CS_init(NvFlowContextInterface* iface, NvFlowContext* context, SolidEmitterPoint4CS_Pipeline* ptr) {
    static const char token[] = "addons/solid/SolidEmitterPoint4CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SolidEmitterPoint4CS_destroy(NvFlowContext* context, SolidEmitterPoint4CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SolidEmitterPoint4CS_PassParams {
    NvFlowBufferTransient* prBoundary;
    NvFlowBufferTransient* prBoundaryControl;
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* gTable;
    NvFlowBufferTransient* arrayValuesIn;
    NvFlowBufferTransient* keyIn;
    NvFlowBufferTransient* valIn;
    NvFlowBufferTransient* keyLowIn;
    NvFlowTextureTransient* valueIn;
    NvFlowSampler* valueSampler;
    NvFlowTextureTransient* coarseValueOut;
};
inline void SolidEmitterPoint4CS_addPassCompute(NvFlowContext* context, SolidEmitterPoint4CS_Pipeline* ptr, NvFlowUint3 gridDim, const SolidEmitterPoint4CS_PassParams* params) {
    NvFlowDescriptorWrite writes[12] = {}; NvFlowResource resources[12] = {};
    writes[0].type = eNvFlowDescriptorType_structuredBuffer; writes[0].write.vulkan.binding = 30;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 31;
    writes[2].type = eNvFlowDescriptorType_constantBuffer; writes[2].write.vulkan.binding = 0;
    writes[3].type = eNvFlowDescriptorType_constantBuffer; writes[3].write.vulkan.binding = 1;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 2;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 3;
    writes[6].type = eNvFlowDescriptorType_structuredBuffer; writes[6].write.vulkan.binding = 4;
    writes[7].type = eNvFlowDescriptorType_structuredBuffer; writes[7].write.vulkan.binding = 5;
    writes[8].type = eNvFlowDescriptorType_structuredBuffer; writes[8].write.vulkan.binding = 6;
    writes[9].type = eNvFlowDescriptorType_texture; writes[9].write.vulkan.binding = 7;
    writes[10].type = eNvFlowDescriptorType_sampler; writes[10].write.vulkan.binding = 8;
    writes[11].type = eNvFlowDescriptorType_rwTexture; writes[11].write.vulkan.binding = 9;
    resources[0].bufferTransient = params->prBoundary;
    resources[1].bufferTransient = params->prBoundaryControl;
    resources[2].bufferTransient = params->gParams;
    resources[3].bufferTransient = params->gSubStepParams;
    resources[4].bufferTransient = params->gTable;
    resources[5].bufferTransient = params->arrayValuesIn;
    resources[6].bufferTransient = params->keyIn;
    resources[7].bufferTransient = params->valIn;
    resources[8].bufferTransient = params->keyLowIn;
    resources[9].textureTransient = params->valueIn;
    resources[10].sampler = params->valueSampler;
    resources[11].textureTransient = params->coarseValueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 12; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SolidEmitterPoint4CS";
    ptr->iface->addPassCompute(context, &pass);
}
