// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SolidEmitterPointClearMarkedCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SolidEmitterPointClearMarkedCS_init(NvFlowContextInterface* iface, NvFlowContext* context, SolidEmitterPointClearMarkedCS_Pipeline* ptr) {
    static const char token[] = "addons/solid/SolidEmitterPointClearMarkedCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SolidEmitterPointClearMarkedCS_destroy(NvFlowContext* context, SolidEmitterPointClearMarkedCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SolidEmitterPointClearMarkedCS_PassParams {
    NvFlowBufferTransient* prBoundary;
    NvFlowBufferTransient* prBoundaryControl;
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowTextureTransient* voxelWeightIn;
    NvFlowTextureTransient* valueOut;
};
inline void SolidEmitterPointClearMarkedCS_addPassCompute(NvFlowContext* context, SolidEmitterPointClearMarkedCS_Pipeline* ptr, NvFlowUint3 gridDim, const SolidEmitterPointClearMarkedCS_PassParams* params) {
    NvFlowDescriptorWrite writes[6] = {}; NvFlowResource resources[6] = {};
    writes[0].type = eNvFlowDescriptorType_structuredBuffer; writes[0].write.vulkan.binding = 30;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 31;
    writes[2].type = eNvFlowDescriptorType_constantBuffer; writes[2].write.vulkan.binding = 0;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 1;
    writes[4].type = eNvFlowDescriptorType_texture; writes[4].write.vulkan.binding = 2;
    writes[5].type = eNvFlowDescriptorType_rwTexture; writes[5].write.vulkan.binding = 3;
    resources[0].bufferTransient = params->prBoundary;
    resources[1].bufferTransient = params->prBoundaryControl;
    resources[2].bufferTransient = params->globalParamsIn;
    resources[3].bufferTransient = params->tableIn;
    resources[4].textureTransient = params->voxelWeightIn;
    resources[5].textureTransient = params->valueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 6; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SolidEmitterPointClearMarkedCS";
    ptr->iface->addPassCompute(context, &pass);
}
