// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SolidEmitterPoint3CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SolidEmitterPoint3CS_init(NvFlowContextInterface* iface, NvFlowContext* context, SolidEmitterPoint3CS_Pipeline* ptr) {
    static const char token[] = "addons/solid/SolidEmitterPoint3CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SolidEmitterPoint3CS_destroy(NvFlowContext* context, SolidEmitterPoint3CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SolidEmitterPoint3CS_PassParams {
    NvFlowBufferTransient* prBoundary;
    NvFlowBufferTransient* prBoundaryControl;
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* gTable;
    NvFlowBufferTransient* arrayValuesIn;
    NvFlowBufferTransient* oldValueIn;
    NvFlowBufferTransient* keyLowIn;
    NvFlowBufferTransient* keyIn;
    NvFlowBufferTransient* valIn;
    NvFlowBufferTransient* scanTarget1In;
    NvFlowBufferTransient* scanCouple1In;
    NvFlowBufferTransient* scanWeight1In;
    NvFlowBufferTransient* key1In;
    NvFlowTextureTransient* valueOut;
    NvFlowTextureTransient* voxelWeightOut;
};
inline void SolidEmitterPoint3CS_addPassCompute(NvFlowContext* context, SolidEmitterPoint3CS_Pipeline* ptr, NvFlowUint3 gridDim, const SolidEmitterPoint3CS_PassParams* params) {
    NvFlowDescriptorWrite writes[16] = {}; NvFlowResource resources[16] = {};
    writes[0].type = eNvFlowDescriptorType_structuredBuffer; writes[0].write.vulkan.binding = 30;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 31;
    writes[2].type = eNvFlowDescriptorType_constantBuffer; writes[2].write.vulkan.binding = 0;
    writes[3].type = eNvFlowDescriptorType_constantBuffer; writes[3].write.vulkan.binding = 1;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 2;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 3;
    writes[6].type = eNvFlowDescriptorType_structuredBuffer; writes[6].write.vulkan.binding = 4;
    writes[7].type = eNvFlowDescriptorType_structuredBuffer; writes[7].write.vulkan.binding = 5;
    writes[8].type = eNvFlowDescriptorType_structuredBuffer; writes[8].write.vulkan.binding = 6;
    writes[9].type = eNvFlowDescriptorType_structuredBuffer; writes[9].write.vulkan.binding = 7;
    writes[10].type = eNvFlowDescriptorType_structuredBuffer; writes[10].write.vulkan.binding = 8;
    writes[11].type = eNvFlowDescriptorType_structuredBuffer; writes[11].write.vulkan.binding = 9;
    writes[12].type = eNvFlowDescriptorType_structuredBuffer; writes[12].write.vulkan.binding = 10;
    writes[13].type = eNvFlowDescriptorType_structuredBuffer; writes[13].write.vulkan.binding = 11;
    writes[14].type = eNvFlowDescriptorType_rwTexture; writes[14].write.vulkan.binding = 12;
    writes[15].type = eNvFlowDescriptorType_rwTexture; writes[15].write.vulkan.binding = 13;
    resources[0].bufferTransient = params->prBoundary;
    resources[1].bufferTransient = params->prBoundaryControl;
    resources[2].bufferTransient = params->gParams;
    resources[3].bufferTransient = params->gSubStepParams;
    resources[4].bufferTransient = params->gTable;
    resources[5].bufferTransient = params->arrayValuesIn;
    resources[6].bufferTransient = params->oldValueIn;
    resources[7].bufferTransient = params->keyLowIn;
    resources[8].bufferTransient = params->keyIn;
    resources[9].bufferTransient = params->valIn;
    resources[10].bufferTransient = params->scanTarget1In;
    resources[11].bufferTransient = params->scanCouple1In;
    resources[12].bufferTransient = params->scanWeight1In;
    resources[13].bufferTransient = params->key1In;
    resources[14].textureTransient = params->valueOut;
    resources[15].textureTransient = params->voxelWeightOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 16; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SolidEmitterPoint3CS";
    ptr->iface->addPassCompute(context, &pass);
}
