// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SolidPressureJacobiCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SolidPressureJacobiCS_init(NvFlowContextInterface* iface, NvFlowContext* context, SolidPressureJacobiCS_Pipeline* ptr) {
    static const char token[] = "addons/solid/SolidPressureJacobiCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SolidPressureJacobiCS_destroy(NvFlowContext* context, SolidPressureJacobiCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SolidPressureJacobiCS_PassParams {
    NvFlowBufferTransient* prBoundary;
    NvFlowBufferTransient* prBoundaryControl;
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gTable;
    NvFlowTextureTransient* pressureIn;
    NvFlowTextureTransient* pressureOut;
    NvFlowBufferTransient* prPressureFaces;
};
inline void SolidPressureJacobiCS_addPassCompute(NvFlowContext* context, SolidPressureJacobiCS_Pipeline* ptr, NvFlowUint3 gridDim, const SolidPressureJacobiCS_PassParams* params) {
    NvFlowDescriptorWrite writes[7] = {}; NvFlowResource resources[7] = {};
    writes[0].type = eNvFlowDescriptorType_structuredBuffer; writes[0].write.vulkan.binding = 30;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 31;
    writes[2].type = eNvFlowDescriptorType_constantBuffer; writes[2].write.vulkan.binding = 0;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 1;
    writes[4].type = eNvFlowDescriptorType_texture; writes[4].write.vulkan.binding = 2;
    writes[5].type = eNvFlowDescriptorType_rwTexture; writes[5].write.vulkan.binding = 3;
    writes[6].type = eNvFlowDescriptorType_structuredBuffer; writes[6].write.vulkan.binding = 32;
    resources[0].bufferTransient = params->prBoundary;
    resources[1].bufferTransient = params->prBoundaryControl;
    resources[2].bufferTransient = params->gParams;
    resources[3].bufferTransient = params->gTable;
    resources[4].textureTransient = params->pressureIn;
    resources[5].textureTransient = params->pressureOut;
    resources[6].bufferTransient = params->prPressureFaces;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 7; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SolidPressureJacobiCS";
    ptr->iface->addPassCompute(context, &pass);
}
