// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SolidAdvectionVelocity2CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SolidAdvectionVelocity2CS_init(NvFlowContextInterface* iface, NvFlowContext* context, SolidAdvectionVelocity2CS_Pipeline* ptr) {
    static const char token[] = "addons/solid/SolidAdvectionVelocity2CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SolidAdvectionVelocity2CS_destroy(NvFlowContext* context, SolidAdvectionVelocity2CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SolidAdvectionVelocity2CS_PassParams {
    NvFlowBufferTransient* prBoundary;
    NvFlowBufferTransient* prBoundaryControl;
    NvFlowBufferTransient* globalParamsIn;
    NvFlowBufferTransient* layerParamsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowTextureTransient* velocityIn;
    NvFlowTextureTransient* predictIn;
    NvFlowTextureTransient* densityIn;
    NvFlowSampler* valueSampler;
    NvFlowTextureTransient* velocityOut;
    NvFlowTextureTransient* densityCoarseOut;
};
inline void SolidAdvectionVelocity2CS_addPassCompute(NvFlowContext* context, SolidAdvectionVelocity2CS_Pipeline* ptr, NvFlowUint3 gridDim, const SolidAdvectionVelocity2CS_PassParams* params) {
    NvFlowDescriptorWrite writes[11] = {}; NvFlowResource resources[11] = {};
    writes[0].type = eNvFlowDescriptorType_structuredBuffer; writes[0].write.vulkan.binding = 30;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 31;
    writes[2].type = eNvFlowDescriptorType_constantBuffer; writes[2].write.vulkan.binding = 0;
    writes[3].type = eNvFlowDescriptorType_structuredBuffer; writes[3].write.vulkan.binding = 1;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 2;
    writes[5].type = eNvFlowDescriptorType_texture; writes[5].write.vulkan.binding = 3;
    writes[6].type = eNvFlowDescriptorType_texture; writes[6].write.vulkan.binding = 4;
    writes[7].type = eNvFlowDescriptorType_texture; writes[7].write.vulkan.binding = 5;
    writes[8].type = eNvFlowDescriptorType_sampler; writes[8].write.vulkan.binding = 6;
    writes[9].type = eNvFlowDescriptorType_rwTexture; writes[9].write.vulkan.binding = 7;
    writes[10].type = eNvFlowDescriptorType_rwTexture; writes[10].write.vulkan.binding = 8;
    resources[0].bufferTransient = params->prBoundary;
    resources[1].bufferTransient = params->prBoundaryControl;
    resources[2].bufferTransient = params->globalParamsIn;
    resources[3].bufferTransient = params->layerParamsIn;
    resources[4].bufferTransient = params->tableIn;
    resources[5].textureTransient = params->velocityIn;
    resources[6].textureTransient = params->predictIn;
    resources[7].textureTransient = params->densityIn;
    resources[8].sampler = params->valueSampler;
    resources[9].textureTransient = params->velocityOut;
    resources[10].textureTransient = params->densityCoarseOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 11; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SolidAdvectionVelocity2CS";
    ptr->iface->addPassCompute(context, &pass);
}
