// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SolidEmitterMeshApplyCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SolidEmitterMeshApplyCS_init(NvFlowContextInterface* iface, NvFlowContext* context, SolidEmitterMeshApplyCS_Pipeline* ptr) {
    static const char token[] = "addons/solid/SolidEmitterMeshApplyCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SolidEmitterMeshApplyCS_destroy(NvFlowContext* context, SolidEmitterMeshApplyCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SolidEmitterMeshApplyCS_PassParams {
    NvFlowBufferTransient* prBoundary;
    NvFlowBufferTransient* prBoundaryControl;
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gSubStepParams;
    NvFlowBufferTransient* gTable;
    NvFlowBufferTransient* arrayValuesIn;
    NvFlowTextureTransient* valueIn;
    NvFlowTextureTransient* closestIn;
    NvFlowTextureTransient* valueOut;
};
inline void SolidEmitterMeshApplyCS_addPassCompute(NvFlowContext* context, SolidEmitterMeshApplyCS_Pipeline* ptr, NvFlowUint3 gridDim, const SolidEmitterMeshApplyCS_PassParams* params) {
    NvFlowDescriptorWrite writes[9] = {}; NvFlowResource resources[9] = {};
    writes[0].type = eNvFlowDescriptorType_structuredBuffer; writes[0].write.vulkan.binding = 30;
    writes[1].type = eNvFlowDescriptorType_constantBuffer; writes[1].write.vulkan.binding = 31;
    writes[2].type = eNvFlowDescriptorType_constantBuffer; writes[2].write.vulkan.binding = 0;
    writes[3].type = eNvFlowDescriptorType_constantBuffer; writes[3].write.vulkan.binding = 1;
    writes[4].type = eNvFlowDescriptorType_structuredBuffer; writes[4].write.vulkan.binding = 2;
    writes[5].type = eNvFlowDescriptorType_structuredBuffer; writes[5].write.vulkan.binding = 3;
    writes[6].type = eNvFlowDescriptorType_texture; writes[6].write.vulkan.binding = 4;
    writes[7].type = eNvFlowDescriptorType_texture; writes[7].write.vulkan.binding = 5;
    writes[8].type = eNvFlowDescriptorType_rwTexture; writes[8].write.vulkan.binding = 6;
    resources[0].bufferTransient = params->prBoundary;
    resources[1].bufferTransient = params->prBoundaryControl;
    resources[2].bufferTransient = params->gParams;
    resources[3].bufferTransient = params->gSubStepParams;
    resources[4].bufferTransient = params->gTable;
    resources[5].bufferTransient = params->arrayValuesIn;
    resources[6].textureTransient = params->valueIn;
    resources[7].textureTransient = params->closestIn;
    resources[8].textureTransient = params->valueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 9; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SolidEmitterMeshApplyCS";
    ptr->iface->addPassCompute(context, &pass);
}
