// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SparseNanoVdbExportVelocityCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SparseNanoVdbExportVelocityCS_init(NvFlowContextInterface* iface, NvFlowContext* context, SparseNanoVdbExportVelocityCS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/SparseNanoVdbExportVelocityCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SparseNanoVdbExportVelocityCS_destroy(NvFlowContext* context, SparseNanoVdbExportVelocityCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SparseNanoVdbExportVelocityCS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowTextureTransient* velocityIn;
    NvFlowBufferTransient* velocityOut;
    NvFlowBufferTransient* divergenceOut;
};
inline void SparseNanoVdbExportVelocityCS_addPassCompute(NvFlowContext* context, SparseNanoVdbExportVelocityCS_Pipeline* ptr, NvFlowUint3 gridDim, const SparseNanoVdbExportVelocityCS_PassParams* params) {
    NvFlowDescriptorWrite writes[5] = {}; NvFlowResource resources[5] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_texture; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[4].write.vulkan.binding = 4;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->tableIn;
    resources[2].textureTransient = params->velocityIn;
    resources[3].bufferTransient = params->velocityOut;
    resources[4].bufferTransient = params->divergenceOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 5; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SparseNanoVdbExportVelocityCS";
    ptr->iface->addPassCompute(context, &pass);
}
