// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SparseNanoVdbExportDensityCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SparseNanoVdbExportDensityCS_init(NvFlowContextInterface* iface, NvFlowContext* context, SparseNanoVdbExportDensityCS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/SparseNanoVdbExportDensityCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SparseNanoVdbExportDensityCS_destroy(NvFlowContext* context, SparseNanoVdbExportDensityCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SparseNanoVdbExportDensityCS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* tableIn;
    NvFlowTextureTransient* densityIn;
    NvFlowBufferTransient* temperatureOut;
    NvFlowBufferTransient* fuelOut;
    NvFlowBufferTransient* burnOut;
    NvFlowBufferTransient* smokeOut;
    NvFlowBufferTransient* rgbaOut;
    NvFlowBufferTransient* rgbOut;
};
inline void SparseNanoVdbExportDensityCS_addPassCompute(NvFlowContext* context, SparseNanoVdbExportDensityCS_Pipeline* ptr, NvFlowUint3 gridDim, const SparseNanoVdbExportDensityCS_PassParams* params) {
    NvFlowDescriptorWrite writes[9] = {}; NvFlowResource resources[9] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_texture; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[8].write.vulkan.binding = 8;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->tableIn;
    resources[2].textureTransient = params->densityIn;
    resources[3].bufferTransient = params->temperatureOut;
    resources[4].bufferTransient = params->fuelOut;
    resources[5].bufferTransient = params->burnOut;
    resources[6].bufferTransient = params->smokeOut;
    resources[7].bufferTransient = params->rgbaOut;
    resources[8].bufferTransient = params->rgbOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 9; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SparseNanoVdbExportDensityCS";
    ptr->iface->addPassCompute(context, &pass);
}
