// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SparseClearTexture2CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SparseClearTexture2CS_init(NvFlowContextInterface* iface, NvFlowContext* context, SparseClearTexture2CS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/SparseClearTexture2CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SparseClearTexture2CS_destroy(NvFlowContext* context, SparseClearTexture2CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SparseClearTexture2CS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowTextureTransient* valueOut;
};
inline void SparseClearTexture2CS_addPassCompute(NvFlowContext* context, SparseClearTexture2CS_Pipeline* ptr, NvFlowUint3 gridDim, const SparseClearTexture2CS_PassParams* params) {
    NvFlowDescriptorWrite writes[2] = {}; NvFlowResource resources[2] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_rwTexture; writes[1].write.vulkan.binding = 1;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].textureTransient = params->valueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 2; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SparseClearTexture2CS";
    ptr->iface->addPassCompute(context, &pass);
}
