// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SparseCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SparseCS_init(NvFlowContextInterface* iface, NvFlowContext* context, SparseCS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/SparseCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SparseCS_destroy(NvFlowContext* context, SparseCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SparseCS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gTableIn;
    NvFlowBufferTransient* gTableOut;
};
inline void SparseCS_addPassCompute(NvFlowContext* context, SparseCS_Pipeline* ptr, NvFlowUint3 gridDim, const SparseCS_PassParams* params) {
    NvFlowDescriptorWrite writes[3] = {}; NvFlowResource resources[3] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[2].write.vulkan.binding = 2;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gTableIn;
    resources[2].bufferTransient = params->gTableOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 3; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SparseCS";
    ptr->iface->addPassCompute(context, &pass);
}
