// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SparseUploadCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SparseUploadCS_init(NvFlowContextInterface* iface, NvFlowContext* context, SparseUploadCS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/SparseUploadCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SparseUploadCS_destroy(NvFlowContext* context, SparseUploadCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SparseUploadCS_PassParams {
    NvFlowBufferTransient* gParams;
    NvFlowBufferTransient* gTableIn;
    NvFlowBufferTransient* gTable1Out;
    NvFlowBufferTransient* gTable2Out;
};
inline void SparseUploadCS_addPassCompute(NvFlowContext* context, SparseUploadCS_Pipeline* ptr, NvFlowUint3 gridDim, const SparseUploadCS_PassParams* params) {
    NvFlowDescriptorWrite writes[4] = {}; NvFlowResource resources[4] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[3].write.vulkan.binding = 3;
    resources[0].bufferTransient = params->gParams;
    resources[1].bufferTransient = params->gTableIn;
    resources[2].bufferTransient = params->gTable1Out;
    resources[3].bufferTransient = params->gTable2Out;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 4; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SparseUploadCS";
    ptr->iface->addPassCompute(context, &pass);
}
