// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SparseNanoVdbPruneLeavesCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SparseNanoVdbPruneLeavesCS_init(NvFlowContextInterface* iface, NvFlowContext* context, SparseNanoVdbPruneLeavesCS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/SparseNanoVdbPruneLeavesCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SparseNanoVdbPruneLeavesCS_destroy(NvFlowContext* context, SparseNanoVdbPruneLeavesCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SparseNanoVdbPruneLeavesCS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* cacheIn;
    NvFlowBufferTransient* nanovdbSrcIn;
    NvFlowBufferTransient* nanovdbInOut;
};
inline void SparseNanoVdbPruneLeavesCS_addPassCompute(NvFlowContext* context, SparseNanoVdbPruneLeavesCS_Pipeline* ptr, NvFlowUint3 gridDim, const SparseNanoVdbPruneLeavesCS_PassParams* params) {
    NvFlowDescriptorWrite writes[4] = {}; NvFlowResource resources[4] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_structuredBuffer; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_rwStructuredBuffer; writes[3].write.vulkan.binding = 3;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->cacheIn;
    resources[2].bufferTransient = params->nanovdbSrcIn;
    resources[3].bufferTransient = params->nanovdbInOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 4; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SparseNanoVdbPruneLeavesCS";
    ptr->iface->addPassCompute(context, &pass);
}
