// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct SparseClearNew1CS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void SparseClearNew1CS_init(NvFlowContextInterface* iface, NvFlowContext* context, SparseClearNew1CS_Pipeline* ptr) {
    static const char token[] = "source/nvflow/shaders/SparseClearNew1CS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void SparseClearNew1CS_destroy(NvFlowContext* context, SparseClearNew1CS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct SparseClearNew1CS_PassParams {
    NvFlowBufferTransient* paramsIn;
    NvFlowBufferTransient* gTable;
    NvFlowTextureTransient* valueOut;
};
inline void SparseClearNew1CS_addPassCompute(NvFlowContext* context, SparseClearNew1CS_Pipeline* ptr, NvFlowUint3 gridDim, const SparseClearNew1CS_PassParams* params) {
    NvFlowDescriptorWrite writes[3] = {}; NvFlowResource resources[3] = {};
    writes[0].type = eNvFlowDescriptorType_constantBuffer; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_structuredBuffer; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_rwTexture; writes[2].write.vulkan.binding = 2;
    resources[0].bufferTransient = params->paramsIn;
    resources[1].bufferTransient = params->gTable;
    resources[2].textureTransient = params->valueOut;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 3; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "SparseClearNew1CS";
    ptr->iface->addPassCompute(context, &pass);
}
