// Generated by generate_host_headers.py. SPDX-License-Identifier: MIT
#pragma once
#include "NvFlowContext.h"
struct VoxelInterpolateNullCS_Pipeline { NvFlowContextInterface* iface; NvFlowComputePipeline* pipeline; };
inline void VoxelInterpolateNullCS_init(NvFlowContextInterface* iface, NvFlowContext* context, VoxelInterpolateNullCS_Pipeline* ptr) {
    static const char token[] = "source/nvflowext/shaders/VoxelInterpolateNullCS.wgsl";
    NvFlowComputePipelineDesc desc = {}; desc.bytecode.data = token; desc.bytecode.sizeInBytes = sizeof(token);
    ptr->iface = iface; ptr->pipeline = iface->createComputePipeline(context, &desc);
}
inline void VoxelInterpolateNullCS_destroy(NvFlowContext* context, VoxelInterpolateNullCS_Pipeline* ptr) { ptr->iface->destroyComputePipeline(context, ptr->pipeline); }
struct VoxelInterpolateNullCS_PassParams {
    NvFlowTextureTransient* value0;
    NvFlowTextureTransient* value1;
    NvFlowTextureTransient* value2;
    NvFlowTextureTransient* value3;
    NvFlowTextureTransient* value4;
    NvFlowTextureTransient* value5;
    NvFlowTextureTransient* value6;
    NvFlowTextureTransient* value7;
    NvFlowTextureTransient* weight0;
    NvFlowTextureTransient* weight1;
    NvFlowTextureTransient* weight2;
    NvFlowTextureTransient* weight3;
    NvFlowTextureTransient* weight4;
    NvFlowTextureTransient* weight5;
    NvFlowTextureTransient* weight6;
    NvFlowTextureTransient* weight7;
};
inline void VoxelInterpolateNullCS_addPassCompute(NvFlowContext* context, VoxelInterpolateNullCS_Pipeline* ptr, NvFlowUint3 gridDim, const VoxelInterpolateNullCS_PassParams* params) {
    NvFlowDescriptorWrite writes[16] = {}; NvFlowResource resources[16] = {};
    writes[0].type = eNvFlowDescriptorType_rwTexture; writes[0].write.vulkan.binding = 0;
    writes[1].type = eNvFlowDescriptorType_rwTexture; writes[1].write.vulkan.binding = 1;
    writes[2].type = eNvFlowDescriptorType_rwTexture; writes[2].write.vulkan.binding = 2;
    writes[3].type = eNvFlowDescriptorType_rwTexture; writes[3].write.vulkan.binding = 3;
    writes[4].type = eNvFlowDescriptorType_rwTexture; writes[4].write.vulkan.binding = 4;
    writes[5].type = eNvFlowDescriptorType_rwTexture; writes[5].write.vulkan.binding = 5;
    writes[6].type = eNvFlowDescriptorType_rwTexture; writes[6].write.vulkan.binding = 6;
    writes[7].type = eNvFlowDescriptorType_rwTexture; writes[7].write.vulkan.binding = 7;
    writes[8].type = eNvFlowDescriptorType_rwTexture; writes[8].write.vulkan.binding = 8;
    writes[9].type = eNvFlowDescriptorType_rwTexture; writes[9].write.vulkan.binding = 9;
    writes[10].type = eNvFlowDescriptorType_rwTexture; writes[10].write.vulkan.binding = 10;
    writes[11].type = eNvFlowDescriptorType_rwTexture; writes[11].write.vulkan.binding = 11;
    writes[12].type = eNvFlowDescriptorType_rwTexture; writes[12].write.vulkan.binding = 12;
    writes[13].type = eNvFlowDescriptorType_rwTexture; writes[13].write.vulkan.binding = 13;
    writes[14].type = eNvFlowDescriptorType_rwTexture; writes[14].write.vulkan.binding = 14;
    writes[15].type = eNvFlowDescriptorType_rwTexture; writes[15].write.vulkan.binding = 15;
    resources[0].textureTransient = params->value0;
    resources[1].textureTransient = params->value1;
    resources[2].textureTransient = params->value2;
    resources[3].textureTransient = params->value3;
    resources[4].textureTransient = params->value4;
    resources[5].textureTransient = params->value5;
    resources[6].textureTransient = params->value6;
    resources[7].textureTransient = params->value7;
    resources[8].textureTransient = params->weight0;
    resources[9].textureTransient = params->weight1;
    resources[10].textureTransient = params->weight2;
    resources[11].textureTransient = params->weight3;
    resources[12].textureTransient = params->weight4;
    resources[13].textureTransient = params->weight5;
    resources[14].textureTransient = params->weight6;
    resources[15].textureTransient = params->weight7;
    NvFlowPassComputeParams pass = {}; pass.pipeline = ptr->pipeline; pass.gridDim = gridDim;
    pass.numDescriptorWrites = 16; pass.descriptorWrites = writes; pass.resources = resources; pass.debugLabel = "VoxelInterpolateNullCS";
    ptr->iface->addPassCompute(context, &pass);
}
