// SPDX-FileCopyrightText: 2026 Jake Wehmeier (BTSpaniel)
// SPDX-License-Identifier: MIT
// Output: bridge/physx-bulk.d.mts
// Generated by tools/generate_addon_types.py; edit this reviewed template.
import createPhysX from '../types/physx-pe.mjs';
export type PhysXModule = Awaited<ReturnType<typeof createPhysX>>;
export interface BulkSnapshot {
    count: number;
    stride: 7;
    layout: 'px,py,pz,qx,qy,qz,qw';
    /** Borrowed views expire at the next snapshot or WASM memory growth. */
    poses: Float32Array;
    ids: Uint32Array;
}
export class PhysXBulk {
    constructor(module: PhysXModule, options?: { capacity?: number });
    /** Unregister before releasing the actor; actor must belong to this module. */
    add(id: number, actor: InstanceType<PhysXModule['PxRigidActor']>): this;
    remove(id: number): this;
    snapshot(options?: { copy?: boolean }): BulkSnapshot;
    dispose(): void;
}
